<?php
/**
 * AI Boost — Package Installer Script
 * Handles install, upgrade, and uninstall of the pkg_aiboost package.
 * On upgrade from plg_system_joomlaboost: migrates data to new DB tables.
 *
 * @package     AiBoost
 * @copyright   (C) 2025 AI Boost (aiboostnow.com). All rights reserved.
 * @license     GNU General Public License version 2 or later
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;

class Pkg_AiboostInstallerScript
{
    public const VERSION     = '0.50.2';
    public const MIN_PHP     = '8.1.0';
    public const MIN_JOOMLA  = '5.0.0';

    /**
     * Task #566 — AI Boost owns ONLY a fenced block inside the user's
     * robots.txt. These markers MUST stay byte-identical with
     * AiBoost\Lib\RobotsTxtBuilder::{BEGIN,END}_MARKER and the legacy marker;
     * the installer/uninstaller cannot autoload the lib, so they are inlined.
     */
    private const ROBOTS_BEGIN_MARKER  = '# BEGIN AI Boost for Joomla managed block (aiboostnow.com) - do not edit between these markers';
    private const ROBOTS_END_MARKER    = '# END AI Boost for Joomla managed block';
    private const ROBOTS_LEGACY_MARKER = '# Managed by AI Boost';

    /**
     * Strip the AI Boost managed block from existing robots.txt content,
     * preserving any user-authored rules. Mirrors
     * AiBoost\Lib\RobotsTxtBuilder::stripManagedBlock(). Returns '' when the
     * whole file was ours (current fenced-only or legacy pre-fence format).
     */
    private function stripRobotsBlock(string $existing): string
    {
        if ($existing === '') {
            return '';
        }

        // Legacy pre-fence install: the entire file was generated by us.
        if (str_starts_with(ltrim($existing, "\xEF\xBB\xBF \t\r\n"), self::ROBOTS_LEGACY_MARKER)) {
            return '';
        }

        $pattern = '/\n*' . preg_quote(self::ROBOTS_BEGIN_MARKER, '/')
            . '.*?' . preg_quote(self::ROBOTS_END_MARKER, '/') . '[^\n]*\n?/su';

        return (string) preg_replace($pattern, '', $existing);
    }

    /**
     * Task #511 — Route installer log events through the central Logger
     * when the AiBoost\Lib autoloader is already registered. During the
     * very first package install the lib autoloader is not yet wired in,
     * so fall back to native error_log() and keep the install path safe.
     */
    private static function logEvent(string $severity, string $msg): void
    {
        if (class_exists('AiBoost\\Lib\\Logger', false)) {
            try {
                \AiBoost\Lib\Logger::$severity($msg, ['source' => 'pkg_script']);
                return;
            } catch (\Throwable $e) {
                // fall through to error_log
            }
        }
        @error_log('[AiBoost][' . strtoupper($severity) . '] ' . $msg);
    }

    public function preflight(string $type, object $parent): bool
    {
        if (version_compare(PHP_VERSION, self::MIN_PHP, '<')) {
            Factory::getApplication()->enqueueMessage(
                sprintf('AI Boost requires PHP %s or higher. You are running PHP %s.', self::MIN_PHP, PHP_VERSION),
                'error'
            );
            return false;
        }

        if (version_compare(JVERSION, self::MIN_JOOMLA, '<')) {
            Factory::getApplication()->enqueueMessage(
                sprintf('AI Boost requires Joomla %s or higher. You are running Joomla %s.', self::MIN_JOOMLA, JVERSION),
                'error'
            );
            return false;
        }

        return true;
    }

    public function postflight(string $type, object $parent): void
    {
        // v0.7.0 — ensure new tables exist on upgrade
        $this->ensureNewTables();

        // Migration runs on both install and upgrade:
        //   • On upgrade from pkg_aiboost: idempotent upsert skips already-migrated rows.
        //   • On fresh install after running plg_system_joomlaboost: old tables are present
        //     and must be migrated even though this is technically an 'install' of the new
        //     package (users uninstall the old plugin ZIP, then install the new package).
        $this->runDataMigration();

        // v0.32.5 — migrate legacy aggregate `robots_block_scrapers` → per-bot scraper_* keys.
        // MUST run AFTER runDataMigration() so that rows copied from the legacy
        // #__joomlaboost_settings table are also canonicalized in the same postflight pass.
        $this->migrateRobotsBlockScrapers();
        $this->migrateSchemaAuthorEntity();
        // Task #428 — migrate legacy `license_tier` flag into per-SKU map.
        $this->migrateLicenseTierToProSkuMap();
        // Task #565 — perpetual activation backfill (MUST run AFTER the #428
        // migration so an active license_state is already materialised).
        $this->migrateActivateProPerpetual();
        // Task #438 — uninstall legacy aiboost_perf plugin (renamed to aiboost_core).
        $this->migrateAiboostPerfToCore();
        // Task #440 — ensure a stable install_id (UUIDv4) exists so the
        // license-heartbeat endpoint can detect domain/install collisions.
        $this->ensureInstallId();
        // Task #473 — default conflict_mode to "cooperative" so existing
        // installs adopt the new ConflictDetector-friendly behaviour.
        $this->ensureConflictModeDefault();
        // Task #482 — backfill page-level default policy and rewrite legacy
        // per-bot 'default' values to '' so the new radio UI is unambiguous.
        $this->migrateCrawlerDefaultPolicy();
        $this->enablePlugins();

        if (in_array($type, ['install', 'update', 'discover_install'], true)) {
            // Task #566 — (re)generate static artifacts (robots.txt managed
            // block, llms.txt, sitemap) ONLY on a genuine install/update.
            // Calling this unconditionally re-injected the robots.txt block
            // during an uninstall-context postflight, defeating the uninstall
            // strip.
            $this->cleanupStaticFiles();

            // Task #454 — Article OG custom fields are a Pro feature.
            // On Free installs we (a) skip the field upsert and (b) remove any
            // rows we previously installed so the Free admin's article editor
            // is clean. #__fields_values (user-entered overrides) are NEVER
            // touched — they remain in the DB and reappear if the user later
            // upgrades to Pro.
            if ($this->isProInstall()) {
                $this->ensureOgCustomFields();
            } else {
                $this->removeOgCustomFieldsForFree();
                // The admin Health module is a Pro-only surface (it now ships in
                // pkg_aiboost_pro and is published by pkg_script_pro). On a Free
                // install we actively remove any instance + the module extension
                // that older base packages used to ship, so Free has no module.
                $this->removeHealthModuleForFree();
            }

            // Task #455 — relabel the Components → AI Boost menu entry so
            // admins see at a glance whether they're on Free or Pro.
            $this->applyEditionMenuLabel();
        }

        // Task #462 — warn admins who carry a historical `license_tier='pro'`
        // but never installed the pkg_aiboost_pro package. With the manifest
        // codegen + STRICT verifier the Free build no longer silently exposes
        // Pro options, so these users would otherwise wonder where their
        // toggles went.
        $this->warnProLicenseWithoutProPackage();

        if (in_array($type, ['install', 'discover_install'], true)) {
            $this->showInstallMessage();
        } else {
            $this->showUpgradeMessage();
        }

        // Task #527 — installation integrity summary: confirm every expected
        // AI Boost extension installed/enabled and flag leftovers or version
        // mismatches. Uses the exact same audit as the Health tab check.
        $this->showIntegritySummary();
    }

    /**
     * Task #527 — Run the installation integrity audit and enqueue one concise
     * summary message. Informational on a clean result, a warning when anything
     * is missing/disabled/leftover/mismatched. Never blocks the install.
     */
    private function showIntegritySummary(): void
    {
        try {
            $db = Factory::getDbo();

            // The lib autoloader may not be registered yet during the first
            // package install, so require the just-installed file directly.
            if (!class_exists('AiBoost\\Lib\\InstallIntegrity', false)) {
                $file = JPATH_ADMINISTRATOR . '/components/com_aiboost/lib/src/InstallIntegrity.php';
                if (is_file($file)) {
                    require_once $file;
                }
            }
            if (!class_exists('AiBoost\\Lib\\InstallIntegrity', false)) {
                return;
            }

            // Resolve the authoritative package version from the installed
            // Version.php (self::VERSION on the script can lag the build).
            $version = self::VERSION;
            $vfile   = JPATH_ADMINISTRATOR . '/components/com_aiboost/Version.php';
            if (!class_exists('AiBoost\\Version', false) && is_file($vfile)) {
                require_once $vfile;
            }
            if (class_exists('AiBoost\\Version', false)) {
                $version = (string) \AiBoost\Version::VERSION;
            }

            $isPro = \AiBoost\Lib\InstallIntegrity::isProEdition($db);
            $audit = \AiBoost\Lib\InstallIntegrity::audit($db, $isPro, $version);
            $line  = \AiBoost\Lib\InstallIntegrity::summaryLine($audit);

            $hasProblem = !empty($audit['missing'])
                || !empty($audit['disabled'])
                || !empty($audit['orphan'])
                || !empty($audit['mismatch']);

            Factory::getApplication()->enqueueMessage(
                'AI Boost installation integrity: ' . $line
                . ($hasProblem
                    ? ' Open the AI Boost Health tab → Installation Integrity for details.'
                    : ''),
                $hasProblem ? 'warning' : 'message'
            );
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] showIntegritySummary failed: ' . $e->getMessage());
        }
    }

    /**
     * Task #462 — Detect "ghost Pro" installs: settings carry a historical
     * `license_tier='pro'` (set before per-SKU map landed in Task #428) but
     * the Pro package is not physically installed. Show an admin notice with
     * a download link instead of silently rendering as Free.
     */
    private function warnProLicenseWithoutProPackage(): void
    {
        try {
            $db = Factory::getDbo();

            $tables = $db->setQuery(
                'SHOW TABLES LIKE ' . $db->quote($db->getPrefix() . 'aiboost_settings')
            )->loadColumn();
            if (!in_array($db->getPrefix() . 'aiboost_settings', $tables, true)) {
                return;
            }

            $raw = (string) $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('settings_json'))
                    ->from($db->quoteName('#__aiboost_settings'))
                    ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
            )->loadResult();
            if ($raw === '') {
                return;
            }
            $data = json_decode($raw, true) ?: [];
            $tier = strtolower((string) ($data['license_tier'] ?? 'free'));
            if (!in_array($tier, ['pro', 'developer', 'agency'], true)) {
                return;
            }

            // Pro package physically installed?
            $proRow = (int) $db->setQuery(
                $db->getQuery(true)
                    ->select('COUNT(*)')
                    ->from($db->quoteName('#__extensions'))
                    ->where($db->quoteName('type') . ' = ' . $db->quote('package'))
                    ->where($db->quoteName('element') . ' = ' . $db->quote('pkg_aiboost_pro'))
            )->loadResult();
            if ($proRow > 0) {
                return;
            }

            Factory::getApplication()->enqueueMessage(
                'AI Boost: your settings record a Pro licence but the Pro '
                . 'package (pkg_aiboost_pro) is not installed on this site. '
                . 'Pro options are now packaged separately. '
                . 'Download Pro from https://aiboostnow.com/account and install '
                . 'the pkg_aiboost_pro ZIP through Joomla → Install Extensions.',
                'warning'
            );
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] warnProLicenseWithoutProPackage failed: ' . $e->getMessage());
        }
    }

    /**
     * Auto-create the 6 AI Boost OG custom fields on install and update.
     *
     * Logic (idempotent / non-destructive):
     *   - Field group "AI Boost — OpenGraph" is created once if absent.
     *   - Each field: INSERT if absent, UPDATE label/description/fieldparams/note if the
     *     version marker in the `note` column differs, SKIP if already at current version.
     *   - #__fields_values (user-entered article overrides) are NEVER touched.
     *   - Column presence (fieldparams, only_use_in_subform) is detected at runtime
     *     via SHOW COLUMNS so the script works across Joomla 5 and 6.
     */
    private function ensureOgCustomFields(): void
    {
        $context     = 'com_content.article';
        $groupTitle  = 'AI Boost — OpenGraph';
        $version     = self::VERSION;
        $diagnostics = [];

        $fieldDefs = [
            [
                'name'        => 'aiboost_og_title',
                'title'       => 'AI Boost — OG Title',
                'type'        => 'text',
                'description' => 'Override the og:title meta tag. Leave empty to use the article title.',
                'fieldparams' => [],
                'ordering'    => 1,
            ],
            [
                'name'        => 'aiboost_og_description',
                'title'       => 'AI Boost — OG Description',
                'type'        => 'textarea',
                'description' => 'Override the og:description meta tag for this article.',
                'fieldparams' => ['rows' => '3', 'cols' => ''],
                'ordering'    => 2,
            ],
            [
                'name'        => 'aiboost_og_image',
                'title'       => 'AI Boost — OG Image',
                'type'        => 'media',
                'description' => 'Override og:image. Recommended size: 1200x630 px.',
                'fieldparams' => ['directory' => '', 'preview' => 'true'],
                'ordering'    => 3,
            ],
            [
                'name'        => 'aiboost_og_type',
                'title'       => 'AI Boost — OG Type',
                'type'        => 'list',
                'description' => 'Override the og:type meta tag. Defaults to "article" for article pages.',
                'fieldparams' => ['options' => [
                    ['name' => '— default (article) —', 'value' => ''],
                    ['name' => 'Article',               'value' => 'article'],
                    ['name' => 'Website',               'value' => 'website'],
                    ['name' => 'Video',                 'value' => 'video.movie'],
                    ['name' => 'Music',                 'value' => 'music.song'],
                    ['name' => 'Product',               'value' => 'product'],
                ]],
                'ordering'    => 4,
            ],
            [
                'name'        => 'aiboost_og_video',
                'title'       => 'AI Boost — OG Video URL',
                'type'        => 'url',
                'description' => 'Optional og:video URL. Enables video preview cards on Facebook and LinkedIn.',
                'fieldparams' => [],
                'ordering'    => 5,
            ],
            [
                'name'        => 'aiboost_twitter_card',
                'title'       => 'AI Boost — Twitter Card',
                'type'        => 'list',
                'description' => 'Override the twitter:card type. Defaults to summary_large_image.',
                'fieldparams' => ['options' => [
                    ['name' => '— default (summary_large_image) —', 'value' => ''],
                    ['name' => 'Summary Large Image',               'value' => 'summary_large_image'],
                    ['name' => 'Summary',                           'value' => 'summary'],
                ]],
                'ordering'    => 6,
            ],
        ];

        // ── Step 1: get/create group via Joomla stock model ──
        try {
            $groupId = $this->upsertFieldGroup($context, $groupTitle);
            $diagnostics[] = 'Group "' . $groupTitle . '" id=' . $groupId;
        } catch (\Throwable $e) {
            $msg = '[AiBoost] Group create failed: ' . $e->getMessage();
            error_log($msg);
            \Joomla\CMS\Log\Log::add($msg, \Joomla\CMS\Log\Log::ERROR, 'aiboost');
            Factory::getApplication()->enqueueMessage(
                'AI Boost: Could not create field group (' . $e->getMessage()
                . '). Create OG fields manually via Content -> Fields.',
                'warning'
            );
            return;
        }

        // ── Step 2: upsert each field ──
        $created = 0;
        $updated = 0;
        $skipped = 0;
        $failed  = 0;

        foreach ($fieldDefs as $def) {
            try {
                $result = $this->upsertField($context, (int) $groupId, $def, $version);
                $diagnostics[] = $def['name'] . ': ' . $result;
                match ($result) {
                    'created' => $created++,
                    'updated' => $updated++,
                    default   => $skipped++,
                };
            } catch (\Throwable $e) {
                $failed++;
                $errMsg = '[AiBoost] Field "' . $def['name'] . '" failed: ' . $e->getMessage();
                error_log($errMsg);
                \Joomla\CMS\Log\Log::add($errMsg, \Joomla\CMS\Log\Log::ERROR, 'aiboost');
                $diagnostics[] = $def['name'] . ': FAILED — ' . $e->getMessage();
            }
        }

        // ── Step 3: user-visible summary ──
        $msgType = $failed > 0 ? 'warning' : 'message';
        $summary = sprintf(
            'AI Boost: OG custom fields — %d created, %d updated, %d unchanged, %d failed.'
            . ' Visible under <em>Content -> Fields -> Articles</em> in "AI Boost — OpenGraph" group.',
            $created, $updated, $skipped, $failed
        );

        if ($failed > 0) {
            $summary .= '<br><small><strong>Diagnostic log:</strong><br>'
                . implode('<br>', array_map('htmlspecialchars', $diagnostics))
                . '</small>';
        }

        Factory::getApplication()->enqueueMessage($summary, $msgType);
    }

    /**
     * Task #454 — Is this install Pro-licensed?
     *
     * Pro determination at install-time mirrors Dashboard::checkIsProEnabled():
     *   - license_tier ∈ {pro, developer, agency} in #__aiboost_settings.settings_json
     *   - OR dev_license_preview === '1' (developer simulator)
     *   - OR a pkg_aiboost_pro package row exists in #__extensions
     *
     * The third clause matters on a fresh install where the settings row
     * doesn't have a tier yet but Pro is being installed in the same session.
     */
    private function isProInstall(): bool
    {
        try {
            $db = Factory::getDbo();

            // 1. settings-based tier (most common — set after license activation)
            $tables = $db->setQuery(
                'SHOW TABLES LIKE ' . $db->quote($db->getPrefix() . 'aiboost_settings')
            )->loadColumn();
            if (in_array($db->getPrefix() . 'aiboost_settings', $tables, true)) {
                $raw = (string) $db->setQuery(
                    $db->getQuery(true)
                        ->select($db->quoteName('settings_json'))
                        ->from($db->quoteName('#__aiboost_settings'))
                        ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
                )->loadResult();
                if ($raw !== '') {
                    $data = json_decode($raw, true) ?: [];
                    $tier = strtolower((string) ($data['license_tier'] ?? 'free'));
                    if (in_array($tier, ['pro', 'developer', 'agency'], true)) {
                        return true;
                    }
                    if ((string) ($data['dev_license_preview'] ?? '0') === '1') {
                        return true;
                    }
                }
            }

            // 2. Pro package physically installed in #__extensions
            $proRow = (int) $db->setQuery(
                $db->getQuery(true)
                    ->select('COUNT(*)')
                    ->from($db->quoteName('#__extensions'))
                    ->where($db->quoteName('type') . ' = ' . $db->quote('package'))
                    ->where($db->quoteName('element') . ' = ' . $db->quote('pkg_aiboost_pro'))
            )->loadResult();
            if ($proRow > 0) {
                return true;
            }
        } catch (\Throwable $e) {
            // On any error, fail closed → Free (no Pro features installed).
            self::logEvent('warning', '[AiBoost] isProInstall() failed, defaulting to Free: ' . $e->getMessage());
        }
        return false;
    }

    /**
     * Task #454 — Remove AI Boost OG custom fields + their group from a
     * Free install.
     *
     * Ownership is verified BOTH ways:
     *   - fields must carry our ownership marker `note LIKE 'aiboost_version:%'`
     *     (written by upsertField()), in addition to matching our context +
     *     known field name. This prevents collateral damage if a third party
     *     happens to use a colliding field name.
     *   - the group must have `description LIKE 'AI Boost%'`.
     *
     * `#__fields_values` rows for the deleted field IDs are explicitly
     * removed (NOT preserved). Joomla generates new field IDs on re-create,
     * so any preserved values would orphan or rebind to the wrong field on a
     * later Pro reinstall — better to delete cleanly so a later Pro install
     * starts from a known empty state. Overrides on Free were a packaging
     * leak that should not have existed in the first place.
     *
     * Idempotent + silent no-op when the group/fields aren't present.
     */
    private function removeOgCustomFieldsForFree(): void
    {
        $context    = 'com_content.article';
        $groupTitle = 'AI Boost — OpenGraph';
        $fieldNames = [
            'aiboost_og_title', 'aiboost_og_description', 'aiboost_og_image',
            'aiboost_og_type', 'aiboost_og_video', 'aiboost_twitter_card',
        ];

        $removedFields = 0;
        $removedGroups = 0;
        $removedValues = 0;

        try {
            $db = Factory::getDbo();

            // Find our group (description marker = our installer)
            $groupId = (int) $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('id'))
                    ->from($db->quoteName('#__fields_groups'))
                    ->where($db->quoteName('context') . ' = ' . $db->quote($context))
                    ->where($db->quoteName('title') . ' = ' . $db->quote($groupTitle))
                    ->where($db->quoteName('description') . ' LIKE ' . $db->quote('AI Boost%'))
            )->loadResult();

            // Only fields carrying our ownership marker `note LIKE 'aiboost_version:%'`
            // are candidates for deletion — exact name match alone is not enough.
            $fieldsQuoted = implode(',', array_map([$db, 'quote'], $fieldNames));
            $fieldIds = $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('id'))
                    ->from($db->quoteName('#__fields'))
                    ->where($db->quoteName('context') . ' = ' . $db->quote($context))
                    ->where($db->quoteName('name') . ' IN (' . $fieldsQuoted . ')')
                    ->where($db->quoteName('note') . ' LIKE ' . $db->quote('aiboost_version:%'))
            )->loadColumn() ?: [];

            // Drop per-article values for our fields BEFORE deleting the field
            // rows. Field IDs change on re-create, so keeping these rows would
            // produce orphans (or rebind to a wrong, foreign field).
            if (!empty($fieldIds)) {
                $idsList = implode(',', array_map('intval', $fieldIds));
                try {
                    $db->setQuery(
                        'DELETE FROM ' . $db->quoteName('#__fields_values')
                        . ' WHERE ' . $db->quoteName('field_id') . ' IN (' . $idsList . ')'
                    )->execute();
                    $removedValues = (int) $db->getAffectedRows();
                } catch (\Throwable $inner) {
                    self::logEvent('warning', '[AiBoost] Could not delete OG field values: ' . $inner->getMessage());
                }
            }

            foreach ($fieldIds as $fieldId) {
                try {
                    $model = Factory::getApplication()->bootComponent('com_fields')
                        ->getMVCFactory()
                        ->createModel('Field', 'Administrator', ['ignore_request' => true]);
                    if ($model->delete($fieldId)) {
                        $removedFields++;
                    }
                } catch (\Throwable $inner) {
                    self::logEvent('warning', '[AiBoost] Could not delete OG field id=' . $fieldId . ': ' . $inner->getMessage());
                }
            }

            // Delete the now-empty group only if its description marker matched
            // ours (already enforced in the SELECT above; $groupId > 0 implies
            // verified ownership).
            if ($groupId > 0) {
                try {
                    $gModel = Factory::getApplication()->bootComponent('com_fields')
                        ->getMVCFactory()
                        ->createModel('Group', 'Administrator', ['ignore_request' => true]);
                    if ($gModel->delete($groupId)) {
                        $removedGroups++;
                    }
                } catch (\Throwable $inner) {
                    self::logEvent('warning', '[AiBoost] Could not delete OG group id=' . $groupId . ': ' . $inner->getMessage());
                }
            }

            if ($removedFields > 0 || $removedGroups > 0) {
                Factory::getApplication()->enqueueMessage(
                    sprintf(
                        'AI Boost (Free): removed %d Pro article custom field(s), %d group(s), and %d stored value(s). '
                        . 'Article OG overrides are a Pro feature — upgrade to Pro to re-enable them.',
                        $removedFields,
                        $removedGroups,
                        $removedValues
                    ),
                    'message'
                );
            }
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] removeOgCustomFieldsForFree failed: ' . $e->getMessage());
        }
    }

    /**
     * Task #455 — Set the admin Components → AI Boost menu label to reflect
     * the installed edition: "AI Boost Free" (Free) or "AI Boost Pro" (Pro).
     *
     * Joomla renders #__menu.title through Text::_(), so we store a language
     * key (COM_AIBOOST_MENU_FREE / COM_AIBOOST_MENU_PRO) — both defined in
     * com_aiboost.sys.ini — rather than literal text. The component slug
     * (option=com_aiboost), alias, and link all stay untouched, so existing
     * bookmarks, ACL rules, and routes keep working.
     *
     * Idempotent: re-running on the same edition is a no-op. Switching tiers
     * (e.g. installing Pro after Free, or letting Pro lapse) flips the label
     * automatically on the next package install/update.
     */
    private function applyEditionMenuLabel(): void
    {
        $newTitle = $this->isProInstall() ? 'COM_AIBOOST_MENU_PRO' : 'COM_AIBOOST_MENU_FREE';

        try {
            $db = Factory::getDbo();

            // Tight predicate: only the top-level admin Components → AI Boost
            // entry. We require client_id=1 (admin), type='component' (the
            // root component menu row, not a submenu/url/separator), a link
            // that targets com_aiboost, and a title equal to one of OUR
            // language keys. Admin-customized labels (anything not in this
            // exact set) are preserved untouched.
            $query = $db->getQuery(true)
                ->update($db->quoteName('#__menu'))
                ->set($db->quoteName('title') . ' = ' . $db->quote($newTitle))
                ->where($db->quoteName('client_id') . ' = 1')
                ->where($db->quoteName('type') . ' = ' . $db->quote('component'))
                ->where($db->quoteName('link') . ' LIKE ' . $db->quote('%option=com_aiboost%'))
                ->where($db->quoteName('title') . ' IN ('
                    . $db->quote('COM_AIBOOST_MENU') . ','
                    . $db->quote('COM_AIBOOST_MENU_FREE') . ','
                    . $db->quote('COM_AIBOOST_MENU_PRO') . ')');
            $db->setQuery($query)->execute();
        } catch (\Throwable $e) {
            // Non-fatal — package still installs; admins can rename manually.
            self::logEvent('warning', '[AiBoost] applyEditionMenuLabel failed: ' . $e->getMessage());
        }
    }

    /**
     * Get or create a Fields group using Joomla's stock administrator model.
     * Joomla model handles asset_id, checked_out, timestamps, language etc.
     */
    private function upsertFieldGroup(string $context, string $title): int
    {
        $db = Factory::getDbo();

        // Try to find existing
        $query = $db->getQuery(true)
            ->select($db->quoteName('id'))
            ->from('#__fields_groups')
            ->where($db->quoteName('context') . '=' . $db->quote($context))
            ->where($db->quoteName('title')   . '=' . $db->quote($title));
        $db->setQuery($query, 0, 1);
        $existingId = (int) ($db->loadResult() ?? 0);

        if ($existingId > 0) {
            return $existingId;
        }

        // Use Joomla stock Group model — handles all required columns automatically
        $model = Factory::getApplication()->bootComponent('com_fields')
            ->getMVCFactory()
            ->createModel('Group', 'Administrator', ['ignore_request' => true]);

        $data = [
            'id'          => 0,
            'context'     => $context,
            'title'       => $title,
            'description' => 'AI Boost per-article OpenGraph override fields',
            'state'       => 1,
            'access'      => 1,
            'language'    => '*',
            'note'        => 'aiboost',
            'params'      => [],
        ];

        if (!$model->save($data)) {
            throw new \RuntimeException('Joomla GroupModel rejected save: ' . $model->getError());
        }

        return (int) $model->getState($model->getName() . '.id');
    }

    /**
     * Upsert a single OG custom field using Joomla's stock administrator model.
     * Returns 'created' | 'updated' | 'skipped'.
     */
    private function upsertField(string $context, int $groupId, array $def, string $version): string
    {
        $db   = Factory::getDbo();
        $note = 'aiboost_version:' . $version;

        // Look up existing field by name+context
        $query = $db->getQuery(true)
            ->select([$db->quoteName('id'), $db->quoteName('note')])
            ->from('#__fields')
            ->where($db->quoteName('name')    . '=' . $db->quote($def['name']))
            ->where($db->quoteName('context') . '=' . $db->quote($context));
        $db->setQuery($query, 0, 1);
        $existing = $db->loadObject();

        // Skip if same version already installed
        if ($existing !== null && trim((string) $existing->note) === $note) {
            return 'skipped';
        }

        $model = Factory::getApplication()->bootComponent('com_fields')
            ->getMVCFactory()
            ->createModel('Field', 'Administrator', ['ignore_request' => true]);

        $data = [
            'id'            => $existing !== null ? (int) $existing->id : 0,
            'context'       => $context,
            'group_id'      => $groupId,
            'title'         => $def['title'],
            'name'          => $def['name'],
            'label'         => $def['title'],
            'default_value' => '',
            'type'          => $def['type'],
            'note'          => $note,
            'description'   => $def['description'],
            'state'         => 1,
            'language'      => '*',
            'ordering'      => (int) $def['ordering'],
            'access'        => 1,
            'params'        => [],
            'fieldparams'   => $def['fieldparams'],
            // No assigned_cat_ids = field is shown for ALL categories (Joomla default)
            // Passing [-1] would HIDE the field from every article — common mistake.
        ];

        if (!$model->save($data)) {
            throw new \RuntimeException('Joomla FieldModel rejected save: ' . $model->getError());
        }

        return $existing !== null ? 'updated' : 'created';
    }

    /**
     * Write or update static files that must live on disk.
     *
     * LiteSpeed / Apache serve static files directly (bypassing PHP), and
     * standard Joomla .htaccess excludes robots.txt from PHP rewriting:
     *   RewriteCond %{REQUEST_URI} !^/robots.txt
     * So robots.txt MUST be a physical file — we write it here.
     */
    private function cleanupStaticFiles(): void
    {
        $robotsFile = JPATH_ROOT . '/robots.txt';

        // Load current settings to build a proper robots.txt
        $settingsJson = '';
        try {
            $db           = Factory::getDbo();
            $settingsJson = (string) $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('settings_json'))
                    ->from('#__aiboost_settings')
                    ->where($db->quoteName('setting_key') . '=' . $db->quote('main'))
            )->loadResult();
        } catch (\Throwable $e) {
            // Table may not exist yet on fresh install — use defaults
        }

        $settings = $settingsJson ? (json_decode($settingsJson, true) ?? []) : [];

        // Respect the master toggle — when robots.txt management is off we do
        // not touch the user's file here.
        if ((int) ($settings['enable_robots'] ?? 1) !== 1) {
            return;
        }

        $siteUrl = (string) (\Joomla\CMS\Uri\Uri::getInstance()->getScheme()
            . '://' . \Joomla\CMS\Uri\Uri::getInstance()->getHost());

        $existing = is_file($robotsFile) ? (string) @file_get_contents($robotsFile) : '';

        // Task #566 — inject ONLY our fenced block, preserving any user rules.
        // Prefer the canonical lib builder (installed under the component) so the
        // block matches what a settings save would produce; fall back to a
        // minimal inline block if the lib is not loadable during install.
        $builder = JPATH_ADMINISTRATOR . '/components/com_aiboost/lib/src/RobotsTxtBuilder.php';
        if (is_file($builder)) {
            require_once $builder;
        }

        if (class_exists('\\AiBoost\\Lib\\RobotsTxtBuilder')) {
            $content = \AiBoost\Lib\RobotsTxtBuilder::injectManagedBlock($existing, $settings, $siteUrl);
        } else {
            $block = $this->buildRobotsBlockFallback($settings, $siteUrl);
            $clean = rtrim($this->stripRobotsBlock($existing));
            $content = $clean === '' ? $block : $clean . "\n\n" . $block;
        }

        @file_put_contents($robotsFile, $content);
    }

    /**
     * Minimal fenced managed block used only when AiBoost\Lib\RobotsTxtBuilder
     * cannot be autoloaded during install. Mirrors the lib's header section.
     *
     * @param array<string,mixed> $settings
     */
    private function buildRobotsBlockFallback(array $settings, string $siteUrl): string
    {
        $lines = [
            self::ROBOTS_BEGIN_MARKER,
            '',
            'User-agent: *',
            'Allow: /',
            '',
            '# Joomla system paths',
            'Disallow: /administrator/',
            'Disallow: /api/',
            'Disallow: /bin/',
            'Disallow: /cache/',
            'Disallow: /cli/',
            'Disallow: /components/',
            'Disallow: /includes/',
            'Disallow: /installation/',
            'Disallow: /language/',
            'Disallow: /layouts/',
            'Disallow: /libraries/',
            'Disallow: /logs/',
            'Disallow: /modules/',
            'Disallow: /plugins/',
            'Disallow: /tmp/',
            '',
            '# Allow public assets',
            'Allow: /templates/',
            'Allow: /media/',
            'Allow: /images/',
        ];
        if (!isset($settings['enable_sitemap']) || (string) $settings['enable_sitemap'] !== '0') {
            $lines[] = '';
            $lines[] = "Sitemap: {$siteUrl}/sitemap.xml";
        }
        $lines[] = '';
        $lines[] = self::ROBOTS_END_MARKER;

        return implode("\n", $lines) . "\n";
    }

    /**
     * Task #438 — rename plg_system_aiboost_perf → plg_system_aiboost_core.
     *
     * Joomla's installer does not automatically uninstall a plugin whose slug changed.
     * This method:
     *   1. Detects if plg_system_aiboost_perf is still installed.
     *   2. Transfers its enabled state to the new plg_system_aiboost_core row.
     *   3. Uninstalls the legacy plg_system_aiboost_perf cleanly.
     *
     * Idempotent — no-op if the legacy plugin row is not present.
     */
    private function migrateAiboostPerfToCore(): void
    {
        try {
            $db = Factory::getDbo();

            $oldId = (int) $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('extension_id'))
                    ->from($db->quoteName('#__extensions'))
                    ->where($db->quoteName('element') . ' = ' . $db->quote('aiboost_perf'))
                    ->where($db->quoteName('type') . ' = ' . $db->quote('plugin'))
                    ->where($db->quoteName('folder') . ' = ' . $db->quote('system'))
            )->loadResult();

            if ($oldId === 0) {
                return;
            }

            // Read old enabled state, transfer to aiboost_core if it was on.
            $wasEnabled = (int) $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('enabled'))
                    ->from($db->quoteName('#__extensions'))
                    ->where($db->quoteName('extension_id') . ' = ' . $oldId)
            )->loadResult();

            if ($wasEnabled === 1) {
                $db->setQuery(
                    $db->getQuery(true)
                        ->update($db->quoteName('#__extensions'))
                        ->set($db->quoteName('enabled') . ' = 1')
                        ->where($db->quoteName('element') . ' = ' . $db->quote('aiboost_core'))
                        ->where($db->quoteName('type') . ' = ' . $db->quote('plugin'))
                        ->where($db->quoteName('folder') . ' = ' . $db->quote('system'))
                )->execute();
            }

            // Uninstall the legacy plugin (removes files + extensions row).
            $installer = new \Joomla\CMS\Installer\Installer();
            $installer->uninstall('plugin', $oldId);

            Factory::getApplication()->enqueueMessage(
                'AI Boost: legacy plugin aiboost_perf was uninstalled and replaced by aiboost_core.',
                'message'
            );
        } catch (\Throwable $e) {
            Factory::getApplication()->enqueueMessage(
                'Warning: Could not uninstall legacy aiboost_perf plugin automatically. '
                . 'Please uninstall it manually in Extensions → Manage. (' . $e->getMessage() . ')',
                'warning'
            );
        }
    }

    /**
     * Task #440 — write a stable UUIDv4 `install_id` into
     * #__aiboost_settings.settings_json (key=`main`) on the first install
     * or upgrade where it is missing. Idempotent — never rewrites an
     * existing id, so domain binding on the heartbeat server stays stable
     * across upgrades.
     */
    private function ensureInstallId(): void
    {
        try {
            $db = Factory::getDbo();
            $tables = $db->setQuery(
                'SHOW TABLES LIKE ' . $db->quote($db->getPrefix() . 'aiboost_settings')
            )->loadColumn();
            if (!in_array($db->getPrefix() . 'aiboost_settings', $tables, true)) {
                return;
            }

            $existingJson = $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('settings_json'))
                    ->from($db->quoteName('#__aiboost_settings'))
                    ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
            )->loadResult();

            $data = $existingJson ? (json_decode((string) $existingJson, true) ?? []) : [];
            if (!empty($data['install_id'])) {
                return;
            }

            $data['install_id'] = $this->generateUuidV4();
            $newJson = json_encode($data, JSON_UNESCAPED_SLASHES);

            if ($existingJson === null) {
                $db->setQuery(
                    $db->getQuery(true)
                        ->insert($db->quoteName('#__aiboost_settings'))
                        ->columns([$db->quoteName('setting_key'), $db->quoteName('settings_json')])
                        ->values($db->quote('main') . ', ' . $db->quote($newJson))
                )->execute();
            } else {
                $db->setQuery(
                    $db->getQuery(true)
                        ->update($db->quoteName('#__aiboost_settings'))
                        ->set($db->quoteName('settings_json') . ' = ' . $db->quote($newJson))
                        ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
                )->execute();
            }
        } catch (\Throwable $e) {
            Factory::getApplication()->enqueueMessage(
                'Warning: Could not generate install_id for license heartbeat. ('
                . $e->getMessage() . ')',
                'warning'
            );
        }
    }

    /**
     * Task #473 — back-fill conflict_mode='cooperative' for installs that
     * predate the new field. Only writes when the key is missing entirely;
     * never overwrites an admin-chosen value. Safe to re-run.
     */
    private function ensureConflictModeDefault(): void
    {
        try {
            $db = Factory::getDbo();
            $tables = $db->setQuery(
                'SHOW TABLES LIKE ' . $db->quote($db->getPrefix() . 'aiboost_settings')
            )->loadColumn();
            if (!in_array($db->getPrefix() . 'aiboost_settings', $tables, true)) {
                return;
            }

            $existingJson = $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('settings_json'))
                    ->from($db->quoteName('#__aiboost_settings'))
                    ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
            )->loadResult();
            if ($existingJson === null) {
                return; // ensureInstallId / first-run path will seed defaults.
            }

            $data = json_decode((string) $existingJson, true) ?? [];
            if (array_key_exists('conflict_mode', $data)) {
                return; // admin already chose a value.
            }

            $data['conflict_mode'] = 'cooperative';
            $newJson = json_encode($data, JSON_UNESCAPED_SLASHES);
            $db->setQuery(
                $db->getQuery(true)
                    ->update($db->quoteName('#__aiboost_settings'))
                    ->set($db->quoteName('settings_json') . ' = ' . $db->quote($newJson))
                    ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
            )->execute();
        } catch (\Throwable $e) {
            // Non-fatal — DocumentInspector falls back to 'cooperative' anyway.
        }
    }

    /**
     * Task #482 — Migrate AI crawler rules to the new page-level default
     * policy model.
     *
     * Two-step backfill, idempotent and safe to re-run:
     *   1. If `aeo_crawler_default_policy` is missing, set it to 'allow'
     *      (preserves the prior "Default = follow global robots.txt"
     *      semantics — the section emitted no per-bot block at all, which
     *      effectively allowed every bot via robots.txt's User-agent: *).
     *   2. Rewrite any per-bot 'default' value in `crawler_bot_rules` to
     *      '' (empty) so the new radio UI starts unselected and the
     *      builder uses the page-level policy as the fallback.
     */
    private function migrateCrawlerDefaultPolicy(): void
    {
        try {
            $db = Factory::getDbo();
            $tables = $db->setQuery(
                'SHOW TABLES LIKE ' . $db->quote($db->getPrefix() . 'aiboost_settings')
            )->loadColumn();
            if (!in_array($db->getPrefix() . 'aiboost_settings', $tables, true)) {
                return;
            }

            $existingJson = $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('settings_json'))
                    ->from($db->quoteName('#__aiboost_settings'))
                    ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
            )->loadResult();
            if ($existingJson === null) {
                return;
            }

            $data    = json_decode((string) $existingJson, true) ?? [];
            $changed = false;

            if (!array_key_exists('aeo_crawler_default_policy', $data)
                || $data['aeo_crawler_default_policy'] === ''
                || $data['aeo_crawler_default_policy'] === null) {
                $data['aeo_crawler_default_policy'] = 'allow';
                $changed = true;
            }

            if (array_key_exists('crawler_bot_rules', $data)) {
                $rules = json_decode((string) $data['crawler_bot_rules'], true);
                if (is_array($rules)) {
                    $rewritten = false;
                    // Only rewrite the legacy literal value 'default' (the
                    // dropdown option that no longer exists) → ''. Preserve
                    // 'allow', 'block', and legacy 'disallow' (which the
                    // builder still honours as block for backward compat).
                    foreach ($rules as $botId => $value) {
                        if (strtolower(trim((string) $value)) === 'default') {
                            $rules[$botId] = '';
                            $rewritten = true;
                        }
                    }
                    if ($rewritten) {
                        $data['crawler_bot_rules'] = json_encode($rules, JSON_UNESCAPED_SLASHES);
                        $changed = true;
                    }
                }
            }

            if (!$changed) {
                return;
            }

            $newJson = json_encode($data, JSON_UNESCAPED_SLASHES);
            $db->setQuery(
                $db->getQuery(true)
                    ->update($db->quoteName('#__aiboost_settings'))
                    ->set($db->quoteName('settings_json') . ' = ' . $db->quote($newJson))
                    ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
            )->execute();
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] migrateCrawlerDefaultPolicy failed: ' . $e->getMessage());
        }
    }

    private function generateUuidV4(): string
    {
        $bytes    = random_bytes(16);
        $bytes[6] = chr((ord($bytes[6]) & 0x0f) | 0x40);
        $bytes[8] = chr((ord($bytes[8]) & 0x3f) | 0x80);
        $hex = bin2hex($bytes);
        return sprintf(
            '%s-%s-%s-%s-%s',
            substr($hex, 0, 8),
            substr($hex, 8, 4),
            substr($hex, 12, 4),
            substr($hex, 16, 4),
            substr($hex, 20, 12)
        );
    }

    /**
     * Free edition — actively remove the admin Health module.
     *
     * The Health module is a Pro-only surface: it now ships in pkg_aiboost_pro
     * and is published by pkg_script_pro. Older base packages shipped + published
     * it, so existing Free installs (and Free installs upgraded from a build that
     * still bundled it) may carry leftover instances and the module extension.
     * This deletes every admin instance (#__modules + #__modules_menu) and then
     * uninstalls the module extension itself so Free has no module at all.
     *
     * Idempotent and safe: when nothing is present it is a no-op. Each step is
     * guarded so one failure never aborts the rest of postflight.
     */
    private function removeHealthModuleForFree(): void
    {
        try {
            $db = Factory::getDbo();

            // Collect admin instance ids (client_id = 1) for mod_aiboost_health.
            $moduleIds = $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('id'))
                    ->from($db->quoteName('#__modules'))
                    ->where($db->quoteName('module') . ' = ' . $db->quote('mod_aiboost_health'))
                    ->where($db->quoteName('client_id') . ' = 1')
            )->loadColumn();

            if ($moduleIds) {
                $ids = array_map('intval', $moduleIds);
                $idList = implode(',', $ids);
                $db->setQuery(
                    'DELETE FROM ' . $db->quoteName('#__modules_menu')
                    . ' WHERE ' . $db->quoteName('moduleid') . ' IN (' . $idList . ')'
                )->execute();
                $db->setQuery(
                    'DELETE FROM ' . $db->quoteName('#__modules')
                    . ' WHERE ' . $db->quoteName('id') . ' IN (' . $idList . ')'
                )->execute();
            }

            // Uninstall the module extension (removes files + #__extensions row).
            $extId = (int) $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('extension_id'))
                    ->from($db->quoteName('#__extensions'))
                    ->where($db->quoteName('type') . ' = ' . $db->quote('module'))
                    ->where($db->quoteName('element') . ' = ' . $db->quote('mod_aiboost_health'))
                    ->where($db->quoteName('client_id') . ' = 1')
            )->loadResult();

            if ($extId > 0) {
                (new \Joomla\CMS\Installer\Installer())->uninstall('module', $extId);
            }
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] removeHealthModuleForFree failed: ' . $e->getMessage());
        }
    }

    private function enablePlugins(): void
    {
        $plugins = [
            'aiboost_schema', 'aiboost_sitemap', 'aiboost_social',
            'aiboost_analytics', 'aiboost_aeo', 'aiboost_core',
        ];

        try {
            $db = Factory::getDbo();

            // Bulk enable using LIKE — safer than exact element names
            $query = $db->getQuery(true)
                ->update('#__extensions')
                ->set($db->quoteName('enabled') . '=1')
                ->where($db->quoteName('type')    . '=' . $db->quote('plugin'))
                ->where($db->quoteName('folder')  . '=' . $db->quote('system'))
                ->where($db->quoteName('element') . ' LIKE ' . $db->quote('aiboost_%'));
            $db->setQuery($query)->execute();
            $affected = $db->getAffectedRows();

            // Fallback: also try exact element names in case none matched LIKE
            if ($affected === 0) {
                foreach ($plugins as $element) {
                    $query = $db->getQuery(true)
                        ->update('#__extensions')
                        ->set($db->quoteName('enabled') . '=1')
                        ->where($db->quoteName('type') . '=' . $db->quote('plugin'))
                        ->where($db->quoteName('element') . '=' . $db->quote($element))
                        ->where($db->quoteName('folder') . '=' . $db->quote('system'));
                    $db->setQuery($query)->execute();
                }
            }
        } catch (\Throwable $e) {
            Factory::getApplication()->enqueueMessage(
                'Warning: Could not auto-enable plugins. Please enable them manually in Extensions → Plugins.',
                'warning'
            );
        }
    }

    /**
     * v0.7.0 — CREATE IF NOT EXISTS for new tables.
     * Safe to run on both fresh install and upgrade.
     */
    private function ensureNewTables(): void
    {
        try {
            $db = Factory::getDbo();

            $db->setQuery('CREATE TABLE IF NOT EXISTS `#__aiboost_redirects` (
                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                `from_url` VARCHAR(1000) NOT NULL,
                `to_url` VARCHAR(1000) NOT NULL,
                `redirect_type` SMALLINT UNSIGNED NOT NULL DEFAULT 301,
                `hits` INT UNSIGNED NOT NULL DEFAULT 0,
                `enabled` TINYINT(1) NOT NULL DEFAULT 1,
                `note` VARCHAR(255) NOT NULL DEFAULT \'\',
                `created_at` DATETIME NOT NULL,
                `updated_at` DATETIME NOT NULL,
                PRIMARY KEY (`id`),
                KEY `idx_from_url` (`from_url`(191)),
                KEY `idx_enabled` (`enabled`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci')->execute();

            $db->setQuery('CREATE TABLE IF NOT EXISTS `#__aiboost_404_log` (
                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                `request_url` VARCHAR(2000) NOT NULL,
                `referrer` VARCHAR(2000) NOT NULL DEFAULT \'\',
                `user_agent` VARCHAR(500) NOT NULL DEFAULT \'\',
                `hits` INT UNSIGNED NOT NULL DEFAULT 1,
                `first_seen` DATETIME NOT NULL,
                `last_seen` DATETIME NOT NULL,
                PRIMARY KEY (`id`),
                KEY `idx_request_url` (`request_url`(191)),
                KEY `idx_last_seen` (`last_seen`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci')->execute();

            // Task #511 — central Logger table.
            $db->setQuery('CREATE TABLE IF NOT EXISTS `#__aiboost_error_log` (
                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                `created_at` DATETIME NOT NULL,
                `severity` VARCHAR(16) NOT NULL DEFAULT \'info\',
                `source` VARCHAR(100) NOT NULL DEFAULT \'\',
                `message` VARCHAR(1000) NOT NULL,
                `context_json` MEDIUMTEXT NULL,
                `request_id` VARCHAR(32) NOT NULL DEFAULT \'\',
                PRIMARY KEY (`id`),
                KEY `idx_created_at` (`created_at`),
                KEY `idx_severity` (`severity`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci')->execute();
        } catch (\Throwable $e) {
            Factory::getApplication()->enqueueMessage(
                'AI Boost: Warning — could not create new tables: ' . $e->getMessage(),
                'warning'
            );
        }
    }

    /**
     * v0.32.5 — One-shot migration: convert legacy aggregate
     * `robots_block_scrapers` setting into the canonical per-bot
     * `scraper_*` keys consumed by AeoTab.vue + RobotsTxtManager.
     *
     * Idempotent: only runs when `robots_block_scrapers` is present AND no
     * `scraper_*` keys have been saved yet. After migration the legacy key
     * is removed so the new UI is the single source of truth.
     */
    private function migrateRobotsBlockScrapers(): void
    {
        $scraperKeys = [
            'scraper_ahrefsbot', 'scraper_semrushbot', 'scraper_dotbot',
            'scraper_mj12bot', 'scraper_blexbot', 'scraper_rogerbot',
            'scraper_screamingfrog', 'scraper_sitebulb', 'scraper_siteauditor',
            'scraper_serpstatbot', 'scraper_bytespider', 'scraper_petalbot',
        ];

        try {
            $db = Factory::getDbo();

            // Skip if the new settings table does not yet exist
            $tables = $db->setQuery(
                'SHOW TABLES LIKE ' . $db->quote($db->getPrefix() . 'aiboost_settings')
            )->loadColumn();
            if (!in_array($db->getPrefix() . 'aiboost_settings', $tables, true)) {
                return;
            }

            $rows = $db->setQuery(
                $db->getQuery(true)
                    ->select(['setting_key', 'settings_json'])
                    ->from('#__aiboost_settings')
            )->loadAssocList();

            $now = Factory::getDate()->toSql();

            foreach ($rows as $row) {
                $key  = (string) $row['setting_key'];
                $json = (string) ($row['settings_json'] ?? '{}');
                $data = json_decode($json, true);
                if (!is_array($data)) {
                    continue;
                }

                if (!array_key_exists('robots_block_scrapers', $data)) {
                    continue; // nothing to migrate
                }

                // Skip if user has already saved any per-bot key (canonical model already in use)
                $alreadyMigrated = false;
                foreach ($scraperKeys as $sk) {
                    if (array_key_exists($sk, $data)) {
                        $alreadyMigrated = true;
                        break;
                    }
                }

                $aggregateOn = (string) $data['robots_block_scrapers'] === '1';
                unset($data['robots_block_scrapers']);

                if (!$alreadyMigrated && $aggregateOn) {
                    foreach ($scraperKeys as $sk) {
                        $data[$sk] = '1';
                    }
                }

                $newJson = json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

                $db->setQuery(
                    $db->getQuery(true)
                        ->update('#__aiboost_settings')
                        ->set($db->quoteName('settings_json') . ' = ' . $db->quote($newJson))
                        ->set($db->quoteName('updated_at') . ' = ' . $db->quote($now))
                        ->where($db->quoteName('setting_key') . ' = ' . $db->quote($key))
                )->execute();
            }
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] migrateRobotsBlockScrapers failed: ' . $e->getMessage());
        }
    }

    // v0.50.2 — `migrateCrawlerDisabledBotsToBotRules()` (shipped briefly in
    // v0.50.1 for Task #463) was removed: the package never reached production,
    // so there is no real legacy `crawler_disabled_bots` data to migrate.
    // The settings key itself was also removed from `$allowedSettings` in
    // SettingsController, so the only place it could still appear is in a
    // pre-#463 staging DB row — which is harmless dead JSON.

    /**
     * v0.38.0 — One-shot migration: collapse legacy global Author Entity fields
     * (schema_author_name/job_title/url/linkedin/wikipedia) into a single
     * schema_author_entity_enabled toggle. If ANY of the old fields was set,
     * the toggle is turned on; the old keys are then dropped.
     *
     * Idempotent: skips rows that have already been migrated (no legacy keys present).
     */
    private function migrateSchemaAuthorEntity(): void
    {
        $legacyKeys = [
            'schema_author_name', 'schema_author_job_title',
            'schema_author_url', 'schema_author_linkedin', 'schema_author_wikipedia',
        ];

        try {
            $db = Factory::getDbo();

            $tables = $db->setQuery(
                'SHOW TABLES LIKE ' . $db->quote($db->getPrefix() . 'aiboost_settings')
            )->loadColumn();
            if (!in_array($db->getPrefix() . 'aiboost_settings', $tables, true)) {
                return;
            }

            $rows = $db->setQuery(
                $db->getQuery(true)
                    ->select(['setting_key', 'settings_json'])
                    ->from('#__aiboost_settings')
            )->loadObjectList();

            if (!$rows) {
                return;
            }

            $now = date('Y-m-d H:i:s');

            foreach ($rows as $row) {
                $key  = (string) $row->setting_key;
                $json = (string) $row->settings_json;
                $data = $json !== '' ? (json_decode($json, true) ?: []) : [];

                $hasLegacy = false;
                $anyValue  = false;
                foreach ($legacyKeys as $k) {
                    if (array_key_exists($k, $data)) {
                        $hasLegacy = true;
                        if (trim((string) $data[$k]) !== '') {
                            $anyValue = true;
                        }
                    }
                }
                if (!$hasLegacy) {
                    continue;
                }

                if ($anyValue && empty($data['schema_author_entity_enabled'])) {
                    $data['schema_author_entity_enabled'] = '1';
                }

                foreach ($legacyKeys as $k) {
                    unset($data[$k]);
                }

                $newJson = json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

                $db->setQuery(
                    $db->getQuery(true)
                        ->update('#__aiboost_settings')
                        ->set($db->quoteName('settings_json') . ' = ' . $db->quote($newJson))
                        ->set($db->quoteName('updated_at') . ' = ' . $db->quote($now))
                        ->where($db->quoteName('setting_key') . ' = ' . $db->quote($key))
                )->execute();
            }
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] migrateSchemaAuthorEntity failed: ' . $e->getMessage());
        }
    }

    /**
     * Task #565 — perpetual activation backfill.
     *
     * Existing paid installs predate the `pro_activated` flag. Set it (once)
     * for any install that currently resolves to Pro — an active license_state
     * row, a legacy Pro `license_tier`, or any true `pro_skus` entry — so the
     * new single gate (PluginRegistry::isProActive) keeps them unlocked. Runs
     * unconditionally (its own guard) because migrateLicenseTierToProSkuMap()
     * early-returns on already-migrated installs and would otherwise skip this.
     * Never clears the flag.
     *
     * Task #567 — this backfill only sees LOCAL state. A lapsed past purchaser
     * whose license_state/license_tier/pro_skus markers were cleared slips
     * through here and is left Free. The runtime safety net for that case is
     * AiBoost\Lib\LicenseReconcile (admin-only, throttled): it asks the update
     * server, by install_id, whether this install was ever bound to a real
     * purchase and re-activates Pro perpetually if so.
     */
    private function migrateActivateProPerpetual(): void
    {
        try {
            $db = Factory::getDbo();
            $q  = $db->getQuery(true)
                ->select($db->quoteName('settings_json'))
                ->from($db->quoteName('#__aiboost_settings'))
                ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'));
            $db->setQuery($q, 0, 1);
            $raw = (string) ($db->loadResult() ?? '');
            if ($raw === '') {
                return; // Fresh install — nothing to activate.
            }
            $data = json_decode($raw, true);
            if (!is_array($data)) {
                return;
            }
            if ((string) ($data['pro_activated'] ?? '0') === '1') {
                return; // Already activated — never re-touch.
            }

            $resolvesPro = false;

            // 1. A verified active license_state row.
            if (isset($data['license_state']) && is_array($data['license_state'])) {
                foreach ($data['license_state'] as $st) {
                    if (is_array($st)
                        && trim((string) ($st['key'] ?? '')) !== ''
                        && strtolower((string) ($st['status'] ?? '')) === 'active'
                    ) {
                        $resolvesPro = true;
                        break;
                    }
                }
            }
            // 2. Legacy Pro tier.
            if (!$resolvesPro) {
                $tier = strtolower(trim((string) ($data['license_tier'] ?? 'free')));
                if (in_array($tier, ['pro', 'developer', 'agency', 'professional', 'basic'], true)) {
                    $resolvesPro = true;
                }
            }
            // 3. Legacy per-SKU map with any unlocked SKU.
            if (!$resolvesPro
                && isset($data['pro_skus']) && is_array($data['pro_skus'])
                && array_filter($data['pro_skus'])
            ) {
                $resolvesPro = true;
            }

            if (!$resolvesPro) {
                return; // Genuine Free install — leave it Free.
            }

            $data['pro_activated'] = '1';
            if (empty($data['pro_activated_at'])) {
                $data['pro_activated_at'] = gmdate('c');
            }
            if (empty($data['pro_activated_version'])) {
                $data['pro_activated_version'] = class_exists('AiBoost\\Version')
                    ? \AiBoost\Version::VERSION
                    : 'migrated';
            }

            $update = $db->getQuery(true)
                ->update($db->quoteName('#__aiboost_settings'))
                ->set($db->quoteName('settings_json') . ' = ' . $db->quote(json_encode($data)))
                ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'));
            $db->setQuery($update);
            $db->execute();
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] migrateActivateProPerpetual failed: ' . $e->getMessage());
        }
    }

    /**
     * Task #428 — migrate the legacy single `license_tier` flag inside
     * #__aiboost_settings.settings_json into a forward-compatible per-SKU
     * `pro_skus` structure. The old key is preserved for backward compat
     * with code that still reads it; new code should consult PluginRegistry.
     *
     * Idempotent: re-running yields the same JSON.
     */
    private function migrateLicenseTierToProSkuMap(): void
    {
        try {
            $db = Factory::getDbo();
            $q  = $db->getQuery(true)
                ->select($db->quoteName('settings_json'))
                ->from($db->quoteName('#__aiboost_settings'))
                ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'));
            $db->setQuery($q, 0, 1);
            $raw = (string) ($db->loadResult() ?? '');
            if ($raw === '') {
                return; // No settings row yet — nothing to migrate.
            }
            $data = json_decode($raw, true);
            if (!is_array($data)) {
                return;
            }
            // Task #429 — even if pro_skus is already populated (#428 migration),
            // we must still backfill license_state.bundle when missing so the
            // runtime gate honors legacy paid installs.
            $alreadyMigratedSkus  = isset($data['pro_skus']) && is_array($data['pro_skus']);
            $alreadyHasLicenseSt  = isset($data['license_state']) && is_array($data['license_state'])
                                  && !empty($data['license_state']);
            if ($alreadyMigratedSkus && $alreadyHasLicenseSt) {
                return; // Fully migrated under #429 — nothing to do.
            }

            $tier   = strtolower(trim((string) ($data['license_tier'] ?? 'free')));
            $proSkus = $alreadyMigratedSkus ? $data['pro_skus'] : [];
            $hasPro = in_array($tier, ['pro', 'developer', 'agency', 'professional', 'basic'], true)
                    || (bool) array_filter($proSkus);

            if (!$alreadyMigratedSkus) {
                $data['pro_skus'] = [
                    'schema'   => $hasPro,
                    'aeo'      => $hasPro,
                    'og'       => $hasPro,
                    'hreflang' => $hasPro,
                    'code'     => $hasPro,
                ];
            }

            // Task #429 — also materialise the new per-SKU license_state map
            // so PluginRegistry's runtime gate sees the legacy Pro install as
            // a bundle-level active license. Users can then enter real per-SKU
            // keys via Components → AI Boost → Licenses to refine the picture.
            if ($hasPro && empty($data['license_state'])) {
                $existingKey = trim((string) ($data['license_key'] ?? ''));
                $data['license_state'] = [
                    'bundle' => [
                        'key'         => $existingKey !== '' ? $existingKey : 'MIGRATED-LEGACY-0.41.0',
                        'status'      => 'active',
                        'expires_at'  => null,
                        'verified_at' => gmdate('c'),
                        'activations_remaining' => null,
                        'mock'        => false,
                        'message'     => 'Migrated from legacy license_tier on upgrade to 0.41.0.',
                    ],
                ];
                // Keep license_tier='pro' for plugins that still read it directly.
                $data['license_tier'] = 'pro';
            } else {
                // Free tier — drop the legacy flag entirely so the new
                // license_state path is the single source of truth.
                unset($data['license_tier']);
            }

            $update = $db->getQuery(true)
                ->update($db->quoteName('#__aiboost_settings'))
                ->set($db->quoteName('settings_json') . ' = ' . $db->quote(json_encode($data)))
                ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'));
            $db->setQuery($update);
            $db->execute();
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] migrateLicenseTierToProSkuMap failed: ' . $e->getMessage());
        }
    }

    private function runDataMigration(): void
    {
        try {
            $db = Factory::getDbo();

            $this->migrateSettings($db);
            $this->migrateTranslations($db);
        } catch (\Throwable $e) {
            Factory::getApplication()->enqueueMessage(
                'Data migration notice: ' . $e->getMessage() . ' — Manual import may be needed via AI Boost → Import.',
                'notice'
            );
        }
    }

    private function migrateSettings(\Joomla\Database\DatabaseInterface $db): void
    {
        $prefix         = $db->getPrefix();
        $oldTable       = $prefix . 'joomlaboost_settings';
        $oldTableExists = false;

        try {
            $tables         = $db->setQuery('SHOW TABLES LIKE ' . $db->quote($oldTable))->loadColumn();
            $oldTableExists = in_array($oldTable, $tables, true);
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] Could not check for old settings table: ' . $e->getMessage());
        }

        if (!$oldTableExists) {
            return;
        }

        // Migrate ALL rows — merge into new table (upsert: skip rows whose key already exists)
        $oldRows = $db->setQuery('SELECT * FROM ' . $db->quoteName($oldTable))->loadObjectList();
        $now     = Factory::getDate()->toSql();
        $copied  = 0;
        $skipped = 0;
        $errors  = 0;

        foreach ($oldRows as $row) {
            $key = $row->setting_key ?? 'main';

            // Check if this key already exists in new table
            $exists = (int) $db->setQuery(
                $db->getQuery(true)->select('COUNT(*)')->from('#__aiboost_settings')
                    ->where($db->quoteName('setting_key') . '=' . $db->quote($key))
            )->loadResult();

            if ($exists > 0) {
                $skipped++;
                continue;
            }

            try {
                $db->setQuery(
                    $db->getQuery(true)
                        ->insert('#__aiboost_settings')
                        ->columns(['setting_key', 'settings_json', 'created_at', 'updated_at'])
                        ->values(
                            $db->quote($key) . ',' .
                            $db->quote($row->settings_json ?? '{}') . ',' .
                            $db->quote($now) . ',' .
                            $db->quote($now)
                        )
                )->execute();
                $copied++;
            } catch (\Throwable $e) {
                $errors++;
                self::logEvent('warning', '[AiBoost] Migration error (settings row ' . $key . '): ' . $e->getMessage());
            }
        }

        if ($errors === 0) {
            $this->dropOldTable($db, $oldTable);
            Factory::getApplication()->enqueueMessage(
                sprintf(
                    'AI Boost: Settings migration complete — %d row(s) copied, %d skipped (already existed). Old table removed.',
                    $copied,
                    $skipped
                ),
                'message'
            );
        } else {
            Factory::getApplication()->enqueueMessage(
                sprintf(
                    'AI Boost: Settings migration — %d copied, %d skipped, %d error(s). Old table kept for safety; check error log.',
                    $copied,
                    $skipped,
                    $errors
                ),
                'warning'
            );
        }
    }

    private function migrateTranslations(\Joomla\Database\DatabaseInterface $db): void
    {
        $prefix         = $db->getPrefix();
        $oldTable       = $prefix . 'joomlaboost_translations';
        $oldTableExists = false;

        try {
            $tables         = $db->setQuery('SHOW TABLES LIKE ' . $db->quote($oldTable))->loadColumn();
            $oldTableExists = in_array($oldTable, $tables, true);
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] Could not check for old translations table: ' . $e->getMessage());
        }

        if (!$oldTableExists) {
            return;
        }

        // Migrate ALL rows — merge into new table (upsert: skip rows whose key+lang already exists)
        $now    = Factory::getDate()->toSql();
        $rows   = $db->setQuery('SELECT * FROM ' . $db->quoteName($oldTable))->loadObjectList();
        $copied = 0;
        $skipped = 0;
        $errors  = 0;

        foreach ($rows as $row) {
            $fieldKey = $row->field_key ?? '';
            $langCode = $row->lang_code ?? 'en-GB';

            if ($fieldKey === '') {
                $skipped++;
                continue;
            }

            $exists = (int) $db->setQuery(
                $db->getQuery(true)->select('COUNT(*)')->from('#__aiboost_translations')
                    ->where($db->quoteName('field_key') . '=' . $db->quote($fieldKey))
                    ->where($db->quoteName('lang_code') . '=' . $db->quote($langCode))
            )->loadResult();

            if ($exists > 0) {
                $skipped++;
                continue;
            }

            try {
                $db->setQuery(
                    $db->getQuery(true)
                        ->insert('#__aiboost_translations')
                        ->columns(['field_key', 'lang_code', 'field_value', 'created_at', 'updated_at'])
                        ->values(
                            $db->quote($fieldKey) . ',' .
                            $db->quote($langCode) . ',' .
                            $db->quote($row->field_value ?? '') . ',' .
                            $db->quote($now) . ',' .
                            $db->quote($now)
                        )
                )->execute();
                $copied++;
            } catch (\Throwable $e) {
                $errors++;
                self::logEvent('warning', '[AiBoost] Migration error (translation ' . $fieldKey . '/' . $langCode . '): ' . $e->getMessage());
            }
        }

        if ($errors === 0) {
            $this->dropOldTable($db, $oldTable);
            Factory::getApplication()->enqueueMessage(
                sprintf(
                    'AI Boost: Translations migration complete — %d row(s) copied, %d skipped (already existed). Old table removed.',
                    $copied,
                    $skipped
                ),
                'message'
            );
        } else {
            Factory::getApplication()->enqueueMessage(
                sprintf(
                    'AI Boost: Translations migration — %d copied, %d skipped, %d error(s). Old table kept for safety; check error log.',
                    $copied,
                    $skipped,
                    $errors
                ),
                'warning'
            );
        }
    }

    private function dropOldTable(\Joomla\Database\DatabaseInterface $db, string $tableName): void
    {
        try {
            $db->setQuery('DROP TABLE IF EXISTS ' . $db->quoteName($tableName))->execute();
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] Could not drop old table ' . $tableName . ': ' . $e->getMessage());
            Factory::getApplication()->enqueueMessage(
                'AI Boost: Old table ' . $tableName . ' could not be removed automatically. You may drop it manually.',
                'notice'
            );
        }
    }

    private function showInstallMessage(): void
    {
        Factory::getApplication()->enqueueMessage(
            sprintf(
                '<strong>AI Boost for Joomla v%s installed successfully!</strong><br>'
                . 'All 6 plugins have been enabled automatically.<br>'
                . '<a href="index.php?option=com_aiboost">Open AI Boost Dashboard &rarr;</a>',
                self::VERSION
            ),
            'message'
        );
    }

    private function showUpgradeMessage(): void
    {
        Factory::getApplication()->enqueueMessage(
            sprintf(
                '<strong>AI Boost for Joomla upgraded to v%s.</strong><br>'
                . 'Settings migrated from old plugin tables (if found).<br>'
                . '<a href="index.php?option=com_aiboost">Open AI Boost Dashboard &rarr;</a>',
                self::VERSION
            ),
            'message'
        );
    }

    /**
     * Uninstall: PRESERVE all user data. We deliberately do NOT drop any
     * #__aiboost_* table — a user who accidentally removes the component and
     * reinstalls keeps every setting, redirect, translation, scan and log row.
     * The only state we reset is the licence: the six licence/dev keys are
     * removed (in PHP, read-modify-write) from the `main` #__aiboost_settings
     * row so a reinstall starts with a clean licence state while all
     * configuration and data stay intact.
     *
     * We still remove the front-of-site artifacts we generated (robots.txt
     * managed block, llms.txt, generated sitemap files). robots.txt is only
     * deleted when the file still carries our "Managed by AI Boost" header
     * marker so we never wipe a hand-edited file owned by the admin.
     *
     * Article custom fields: the same ownership-checked cleanup used by
     * removeOgCustomFieldsForFree() is invoked here, so the 6 aiboost_og_*
     * fields, the "AI Boost — OpenGraph" group, and any stored per-article
     * overrides are removed cleanly. The ownership predicate
     * (note LIKE 'aiboost_version:%') ensures third-party fields that
     * happen to share a name are never touched.
     *
     * Media folder (media/com_aiboost/): removed automatically by Joomla's
     * component uninstaller via the <media folder="media" destination=
     * "com_aiboost"> declaration in com_aiboost.xml — no explicit cleanup
     * needed here.
     */
    public function uninstall(object $parent): void
    {
        $db     = Factory::getDbo();
        $errors = [];

        // Article OG custom fields + per-article overrides. Safe to call on
        // every uninstall — the method only deletes rows carrying our own
        // ownership marker.
        try {
            $this->removeOgCustomFieldsForFree();
        } catch (\Throwable $e) {
            self::logEvent('warning', '[AiBoost] Uninstall: OG custom fields cleanup failed: ' . $e->getMessage());
        }

        // Reset ONLY the licence state — never the user's data. Remove the six
        // licence/dev keys from the `main` settings row in PHP (read-modify-write)
        // so a reinstall comes up unlicensed (clean licence state) while every
        // other setting survives. All #__aiboost_* tables are intentionally left
        // in place.
        //
        // We deliberately do NOT use the SQL JSON_REMOVE() function here:
        // settings_json is a NOT NULL MEDIUMTEXT column, and JSON_REMOVE() returns
        // SQL NULL on any parser hiccup. Writing NULL to a NOT NULL column is
        // coerced to '' under a non-strict sql_mode — which a reinstall then reads
        // as an empty settings blob and silently wipes ALL user data. Doing the
        // edit in PHP keeps the round-trip identical to every other helper here.
        $licenceKeys = [
            'license_key',
            'license_email',
            'pro_activated',
            'install_id',
            'dev_license_preview',
            'dev_force_free_tier',
        ];
        try {
            $existingJson = $db->setQuery(
                $db->getQuery(true)
                    ->select($db->quoteName('settings_json'))
                    ->from($db->quoteName('#__aiboost_settings'))
                    ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
            )->loadResult();

            // No row, or an already-empty blob — nothing to reset.
            if (is_string($existingJson) && $existingJson !== '') {
                $data = json_decode($existingJson, true);

                // If the stored value will not parse as a JSON object we leave it
                // ENTIRELY untouched. Overwriting unparseable-but-present settings
                // would lose the user's data — exactly what this task forbids.
                if (is_array($data)) {
                    $changed = false;
                    foreach ($licenceKeys as $k) {
                        if (array_key_exists($k, $data)) {
                            unset($data[$k]);
                            $changed = true;
                        }
                    }

                    if ($changed) {
                        // Encode as an object even when empty so the column never
                        // round-trips as a JSON array ("[]"). The substitute/partial
                        // flags keep a stray bad byte in some unrelated value from
                        // turning the whole encode into `false`.
                        $newJson = $data === []
                            ? '{}'
                            : json_encode(
                                $data,
                                JSON_UNESCAPED_SLASHES
                                | JSON_INVALID_UTF8_SUBSTITUTE
                                | JSON_PARTIAL_OUTPUT_ON_ERROR
                            );

                        // HARD SAFETY: never write an empty/false value. A NULL or
                        // '' here would be read by the next install as "no settings"
                        // and silently wipe ALL user data (the original bug, whether
                        // via SQL JSON_REMOVE→NULL or a failed json_encode→false).
                        // If we cannot produce a non-empty JSON object we abort the
                        // licence reset and keep the row exactly as it was.
                        if (is_string($newJson) && $newJson !== '' && $newJson !== '[]') {
                            $db->setQuery(
                                $db->getQuery(true)
                                    ->update($db->quoteName('#__aiboost_settings'))
                                    ->set($db->quoteName('settings_json') . ' = ' . $db->quote($newJson))
                                    ->where($db->quoteName('setting_key') . ' = ' . $db->quote('main'))
                            )->execute();
                        } else {
                            $errors[] = 'licence wipe';
                            self::logEvent('warning', '[AiBoost] Uninstall: skipped licence reset — re-encoding settings_json yielded an empty/invalid value; user data left intact.');
                        }
                    }
                } else {
                    self::logEvent('warning', '[AiBoost] Uninstall: settings_json for `main` did not decode to an array; left untouched to avoid data loss.');
                }
            }
        } catch (\Throwable $e) {
            $errors[] = 'licence wipe';
            self::logEvent('warning', '[AiBoost] Uninstall: could not wipe licence keys from #__aiboost_settings: ' . $e->getMessage());
        }

        // Remove generated static artifacts. Each removal is independently
        // guarded so one failure (e.g. permissions) does not abort the rest.
        $removedFiles = [];
        $marker       = 'Managed by AI Boost';

        // Task #566 — robots.txt is the user's file: strip ONLY our fenced
        // block. Delete the file outright only when it was entirely ours
        // (fenced-only or legacy pre-fence format → nothing left after strip).
        $robotsPath = JPATH_ROOT . '/robots.txt';
        if (is_file($robotsPath)) {
            $existing = (string) @file_get_contents($robotsPath);
            $stripped = $this->stripRobotsBlock($existing);
            if ($stripped !== $existing) {
                if (trim($stripped) === '') {
                    if (@unlink($robotsPath)) {
                        $removedFiles[] = 'robots.txt';
                    }
                } elseif (@file_put_contents($robotsPath, rtrim($stripped) . "\n") !== false) {
                    $removedFiles[] = 'robots.txt (managed block)';
                }
            }
        }

        foreach (['llms.txt', 'sitemap.xml', 'sitemap-index.xml'] as $file) {
            $path = JPATH_ROOT . '/' . $file;
            if (is_file($path)) {
                $head = (string) @file_get_contents($path, false, null, 0, 256);
                // sitemap.xml: only delete if generated by us (XML comment marker).
                $isOurs = $file === 'llms.txt'
                    ? true
                    : str_contains($head, $marker) || str_contains($head, 'aiboost')
                        || str_contains($head, 'AI Boost');
                if ($isOurs && @unlink($path)) {
                    $removedFiles[] = $file;
                }
            }
        }

        $msgParts = [];
        if (!$errors) {
            $msgParts[] = 'AI Boost package removed. Your data has been preserved '
                . '— all settings, redirects, translations and logs remain in the '
                . 'database, so reinstalling restores everything. Only the licence '
                . 'keys were cleared.';
        } else {
            $msgParts[] = 'AI Boost removed and your data preserved, but the '
                . 'following step(s) could not be completed automatically: '
                . implode(', ', $errors);
        }
        if ($removedFiles) {
            $msgParts[] = 'Removed generated files from site root: '
                . implode(', ', $removedFiles) . '.';
        }

        Factory::getApplication()->enqueueMessage(
            implode(' ', $msgParts),
            $errors ? 'warning' : 'message'
        );
    }
}
