<?php

/**
 * @package     Joomla.Plugin
 * @subpackage  System.JoomlaBoost
 * @version     0.1.17-debug
 */

defined('_JEXEC') or die;

use Joomla\CMS\Plugin\CMSPlugin;
use Joomla\CMS\Application\CMSApplication;
use Joomla\Event\Event;

class PlgSystemJoomlaboostdebug extends CMSPlugin
{
  protected $autoloadLanguage = true;
  protected $app;

  public function __construct(&$subject, $config = [])
  {
    parent::__construct($subject, $config);
    $this->app = $this->getApplication();

    // Debug log - check if constructor is called
    error_log('JoomlaBoost DEBUG: Constructor called');
  }

  public function onAfterInitialise()
  {
    error_log('JoomlaBoost DEBUG: onAfterInitialise called');

    if (!$this->app->isClient('site')) {
      error_log('JoomlaBoost DEBUG: Not site client, exiting');
      return;
    }

    $input = $this->app->input;
    $requestUri = $input->server->getString('REQUEST_URI', '');

    error_log('JoomlaBoost DEBUG: Request URI = ' . $requestUri);

    $this->handleSpecialRequests($requestUri);
  }

  public function onAfterRoute()
  {
    error_log('JoomlaBoost DEBUG: onAfterRoute called');

    if (!$this->app->isClient('site')) {
      error_log('JoomlaBoost DEBUG: Not site client, exiting');
      return;
    }

    $input = $this->app->input;
    $requestUri = $input->server->getString('REQUEST_URI', '');

    error_log('JoomlaBoost DEBUG: onAfterRoute - Request URI = ' . $requestUri);

    $this->handleSpecialRequests($requestUri);
  }

  private function handleSpecialRequests($requestUri)
  {

    // Check for robots.txt request
    if (preg_match('#/robots\.txt$#i', $requestUri)) {
      error_log('JoomlaBoost DEBUG: Robots.txt request detected');
      $this->handleRobotsRequest();
      return;
    }

    // Check for sitemap.xml request  
    if (preg_match('#/sitemap\.xml$#i', $requestUri)) {
      error_log('JoomlaBoost DEBUG: Sitemap.xml request detected');
      $this->handleSitemapRequest();
      return;
    }

    error_log('JoomlaBoost DEBUG: No special request, normal page');
  }

  private function handleRobotsRequest()
  {
    error_log('JoomlaBoost DEBUG: Generating robots.txt');

    $domain = $this->getCurrentDomain();
    $isStaging = $this->isStatingSite($domain);

    error_log('JoomlaBoost DEBUG: Domain = ' . $domain . ', isStaging = ' . ($isStaging ? 'YES' : 'NO'));

    if ($isStaging) {
      $content = "# JoomlaBoost Robots.txt - STAGING ENVIRONMENT (DEBUG)\n"
        . "# This site is not indexed by search engines\n\n"
        . "User-agent: *\n"
        . "Disallow: /\n\n"
        . "# Generated by JoomlaBoost Debug Plugin\n"
        . "# Generated: " . date('Y-m-d H:i:s T') . "\n";
    } else {
      $content = "# JoomlaBoost Robots.txt - PRODUCTION ENVIRONMENT (DEBUG)\n\n"
        . "User-agent: *\n"
        . "Allow: /\n\n"
        . "# Sitemap\n"
        . "Sitemap: {$domain}sitemap.xml\n\n"
        . "# Generated by JoomlaBoost Debug Plugin\n"
        . "# Generated: " . date('Y-m-d H:i:s T') . "\n";
    }

    error_log('JoomlaBoost DEBUG: Sending robots.txt response');

    // Send headers and content
    header('Content-Type: text/plain; charset=UTF-8');
    header('Cache-Control: public, max-age=3600');
    echo $content;

    error_log('JoomlaBoost DEBUG: Robots.txt sent, exiting');
    $this->app->close();
  }

  private function handleSitemapRequest()
  {
    error_log('JoomlaBoost DEBUG: Generating sitemap.xml');

    $domain = $this->getCurrentDomain();
    $lastmod = date('Y-m-d\TH:i:s\Z');
    $isStaging = $this->isStatingSite($domain);
    $env = $isStaging ? 'STAGING' : 'PRODUCTION';

    $content = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
      . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n"
      . "  <!-- JoomlaBoost Sitemap - {$env} ENVIRONMENT (DEBUG) -->\n"
      . "  <url>\n"
      . '    <loc>' . htmlspecialchars($domain) . "</loc>\n"
      . '    <lastmod>' . $lastmod . "</lastmod>\n"
      . "    <changefreq>daily</changefreq>\n"
      . "    <priority>1.0</priority>\n"
      . "  </url>\n"
      . "  <!-- Generated by JoomlaBoost Debug Plugin -->\n"
      . "  <!-- Generated: " . date('Y-m-d H:i:s T') . " -->\n"
      . "</urlset>";

    error_log('JoomlaBoost DEBUG: Sending sitemap.xml response');

    // Send headers and content
    header('Content-Type: application/xml; charset=UTF-8');
    header('Cache-Control: public, max-age=3600');
    echo $content;

    error_log('JoomlaBoost DEBUG: Sitemap.xml sent, exiting');
    $this->app->close();
  }

  private function getCurrentDomain(): string
  {
    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    return $scheme . '://' . $host . '/';
  }

  private function isStatingSite(string $domain): bool
  {
    $stagingKeywords = ['staging', 'stage', 'dev', 'test', 'localhost'];
    foreach ($stagingKeywords as $keyword) {
      if (stripos($domain, $keyword) !== false) {
        return true;
      }
    }
    return false;
  }
}
