<?php

/**
 * JoomlaBoost Plugin - MINIMAL TEST VERSION
 * @version     1.0.0-minimal
 */

\defined('_JEXEC') or die;

use Joomla\CMS\Plugin\CMSPlugin;
use Joomla\CMS\Factory;
use Joomla\CMS\Document\HtmlDocument;
use Joomla\CMS\Application\CMSApplication;

/**
 * JoomlaBoost plugin - MINIMAL TEST VERSION
 */
class PlgSystemJoomlaboost extends CMSPlugin
{
    /**
     * Constructor
     * 
     * @param mixed $subject The object to observe
     * @param array<string, mixed> $config Configuration array
     */
    public function __construct($subject, array $config = [])
    {
        // Set autoload language before parent constructor
        if (!isset($config['autoloadLanguage'])) {
            $config['autoloadLanguage'] = true;
        }
        
        parent::__construct($subject, $config);
    }

    /**
     * Safe application access
     */
    private function getApp(): ?CMSApplication
    {
        try {
            return Factory::getApplication();
        } catch (\Throwable $e) {
            return null;
        }
    }

    /**
     * Early request hook (check robots/sitemap)
     */
    public function onAfterInitialise(): void
    {
        $app = $this->getApp();
        if (!$app) {
            return;
        }

        if (!$app->isClient('site')) {
            // Optional: debug in backend
            if ($app->isClient('administrator')) {
                $this->logDebug('JoomlaBoost initialised (admin)');
            }
            return;
        }

        // robots.txt handling
        if ($this->isRobotsRequest()) {
            $this->handleRobotsRequest($app);
            return;
        }

        // sitemap.xml handling
        if ($this->isSitemapRequest()) {
            $this->handleSitemapRequest($app);
            return;
        }
    }

    /**
     * Modify head (minimal version)
     */
    public function onBeforeCompileHead(): void
    {
        $app = $this->getApp();
        if (!$app || !$app->isClient('site')) {
            return;
        }

        $document = $app->getDocument();
        if (!$document instanceof HtmlDocument) {
            return;
        }

        try {
            // Add basic debugging marker
            $document->addCustomTag('<!-- JoomlaBoost Plugin Active (Minimal) -->');
            $this->logDebug('JoomlaBoost head compilation completed (minimal version)');
        } catch (\Throwable $e) {
            $this->logDebug('Head compilation failed: ' . $e->getMessage());
        }
    }

    private function isSitemapRequest(): bool
    {
        $requestUri = (string) ($_SERVER['REQUEST_URI'] ?? '');
        $cleanUri   = strtok($requestUri, '?') ?: '';

        if (preg_match('#/sitemap\.xml$#i', $cleanUri)) {
            return true;
        }

        return isset($_GET['format']) && (string) $_GET['format'] === 'sitemap';
    }

    private function handleSitemapRequest(CMSApplication $app): void
    {
        header('Content-Type: application/xml; charset=utf-8');
        header('Cache-Control: public, max-age=3600');

        echo $this->generateSitemapContent();
        $app->close();
    }

    private function generateSitemapContent(): string
    {
        $domain    = $this->getCurrentDomain();
        $isStaging = $this->isStaging($domain);
        return $isStaging ? $this->getStagingSitemap() : $this->getProductionSitemap();
    }

    private function getStagingSitemap(): string
    {
        $domain  = $this->getCurrentDomain();
        $lastmod = date('Y-m-d\TH:i:s\Z');

        return '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
            . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n"
            . "  <!-- JoomlaBoost Sitemap - STAGING ENVIRONMENT (MINIMAL) -->\n"
            . "  <!-- Limited sitemap for staging -->\n"
            . "  <url>\n"
            . '    <loc>' . htmlspecialchars($domain) . "</loc>\n"
            . '    <lastmod>' . $lastmod . "</lastmod>\n"
            . "    <changefreq>daily</changefreq>\n"
            . "    <priority>1.0</priority>\n"
            . "  </url>\n"
            . "  <!-- Generated by JoomlaBoost Plugin (MINIMAL) -->\n"
            . "  <!-- Environment: Staging -->\n"
            . "  <!-- Generated: " . date('Y-m-d H:i:s T') . " -->\n"
            . "</urlset>";
    }

    private function getProductionSitemap(): string
    {
        $domain = $this->getCurrentDomain();
        $lastmod = date('Y-m-d\TH:i:s\Z');

        return '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
            . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n"
            . "  <!-- JoomlaBoost Sitemap - PRODUCTION ENVIRONMENT (MINIMAL) -->\n"
            . "  <url>\n"
            . '    <loc>' . htmlspecialchars($domain) . "</loc>\n"
            . '    <lastmod>' . $lastmod . "</lastmod>\n"
            . "    <changefreq>daily</changefreq>\n"
            . "    <priority>1.0</priority>\n"
            . "  </url>\n"
            . "  <!-- TODO: Add menu items and articles dynamically -->\n"
            . "  <!-- Generated by JoomlaBoost Plugin (MINIMAL) -->\n"
            . "  <!-- Environment: Production -->\n"
            . "  <!-- Generated: " . date('Y-m-d H:i:s T') . " -->\n"
            . "</urlset>";
    }

    private function isRobotsRequest(): bool
    {
        $requestUri = (string) ($_SERVER['REQUEST_URI'] ?? '');
        $cleanUri = strtok($requestUri, '?') ?: '';

        if (preg_match('#/robots\.txt$#i', $cleanUri)) {
            return true;
        }

        return isset($_GET['format']) && (string) $_GET['format'] === 'robots';
    }

    private function handleRobotsRequest(CMSApplication $app): void
    {
        header('Content-Type: text/plain');
        header('Cache-Control: public, max-age=3600');

        echo $this->generateRobotsContent();
        $app->close();
    }

    private function generateRobotsContent(): string
    {
        $domain = $this->getCurrentDomain();
        $isStaging = $this->isStaging($domain);
        return $isStaging ? $this->getStagingRobots() : $this->getProductionRobots();
    }

    private function getCurrentDomain(): string
    {
        $scheme = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ? 'https' : 'http';
        $host = $_SERVER['HTTP_HOST'] ?? ($_SERVER['SERVER_NAME'] ?? 'localhost');
        return $scheme . '://' . $host . '/';
    }

    private function isStaging(string $domain): bool
    {
        $stagingKeywords = ['staging', 'stage', 'dev', 'test', 'localhost'];
        foreach ($stagingKeywords as $keyword) {
            if (stripos($domain, $keyword) !== false) {
                return true;
            }
        }
        return false;
    }

    private function getStagingRobots(): string
    {
        return "# JoomlaBoost Robots.txt - STAGING ENVIRONMENT (MINIMAL)\n"
            . "# This site is not indexed by search engines\n\n"
            . "# Allow Google Search Console and related tools for testing\n"
            . "User-agent: Googlebot\n"
            . "User-agent: Google-InspectionTool\n"
            . "User-agent: Google-Site-Verification\n"
            . "User-agent: GoogleOther\n"
            . "Allow: /\n"
            . "Disallow: /administrator/\n"
            . "Disallow: /api/\n"
            . "Disallow: /cache/\n"
            . "Disallow: /tmp/\n\n"
            . "# Block all other crawlers\n"
            . "User-agent: *\n"
            . "Disallow: /\n\n"
            . "# This is a staging environment - not for public indexing\n\n"
            . "# Generated by JoomlaBoost Plugin (MINIMAL)\n"
            . "# Environment: Staging\n"
            . "# Generated: " . date('Y-m-d H:i:s T') . "\n";
    }

    private function getProductionRobots(): string
    {
        $baseUrl = $this->getCurrentDomain();

        return "# JoomlaBoost Robots.txt - PRODUCTION ENVIRONMENT (MINIMAL)\n\n"
            . "User-agent: *\n"
            . "Allow: /\n\n"
            . "# Disallow admin areas\n"
            . "Disallow: /administrator/\n"
            . "Disallow: /cache/\n"
            . "Disallow: /includes/\n"
            . "Disallow: /language/\n"
            . "Disallow: /libraries/\n"
            . "Disallow: /logs/\n"
            . "Disallow: /tmp/\n\n"
            . "# Allow specific files\n"
            . "Allow: /templates/\n"
            . "Allow: /media/\n"
            . "Allow: /images/\n\n"
            . "# Sitemap\n"
            . "Sitemap: {$baseUrl}sitemap.xml\n\n"
            . "# Generated by JoomlaBoost Plugin (MINIMAL)\n"
            . "# Environment: Production\n"
            . "# Generated: " . date('Y-m-d H:i:s T') . "\n";
    }

    private function logDebug(string $message, array $context = []): void
    {
        try {
            if ($this->params && $this->params->get('debug_mode', 0)) {
                $logMessage = '[JoomlaBoost MINIMAL] ' . $message;
                if (!empty($context)) {
                    $logMessage .= ' | ' . json_encode($context, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
                }
                Factory::getApplication()->enqueueMessage($logMessage, 'info');
            }
        } catch (\Throwable $e) {
            // ignore
        }
    }
}

?>
