<?php
/**
 * AI Boost — Schema manifest.
 * Lists every Schema.org-related field with free/pro tier metadata.
 */

defined('_JEXEC') or die;

return [
    // ── Core (free) ────────────────────────────────────────────────
    [
        'key'         => 'enable_schema',
        'tab'         => 'schema',
        'section'     => 'core',
        'label'       => 'Enable Schema.org structured data',
        'type'        => 'toggle',
        'default'     => '1',
        'tier'        => 'free',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'page_type_auto_detect',
        'tab'         => 'schema',
        'section'     => 'core',
        'label'       => 'Auto-detect page type',
        'type'        => 'toggle',
        'default'     => '1',
        'tier'        => 'free',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'schema_type',
        'tab'         => 'schema',
        'section'     => 'business',
        'label'       => 'Schema Type',
        'type'        => 'select',
        'default'     => 'Organization',
        'tier'        => 'free',
        'sku'         => 'schema',
        'options'     => [
            'Organization'              => 'Organization (generic)',
            'LocalBusiness'             => 'LocalBusiness',
            'FoodEstablishment'         => 'Restaurant / Cafe',
            'Restaurant'                => 'Restaurant (specific)',
            'EducationalOrganization'   => 'School / University',
            'LodgingBusiness'           => 'Hotel / Accommodation',
            'MedicalClinic'             => 'Medical Clinic',
            'LegalService'              => 'Lawyer / Law Firm',
            'SportsActivityLocation'    => 'Gym / Sports Club',
            'Dentist'                   => 'Dentist',
            'RealEstateAgent'           => 'Real Estate Agency',
            'AutomotiveBusiness'        => 'Automotive Business',
            'Store'                     => 'Store / Shop',
            'TouristAttraction'         => 'Tourist Attraction',
            'ProfessionalService'       => 'Professional Service',
            'Person'                    => 'Person / Portfolio',
            'NewsMediaOrganization'     => 'News / Media',
        ],
    ],
    [
        'key'         => 'specific_price_range',
        'tab'         => 'schema',
        'section'     => 'business',
        'label'       => 'Price Range',
        'type'        => 'select',
        'default'     => '',
        'tier'        => 'free',
        'sku'         => 'schema',
        'options'     => [
            ''     => 'Not specified',
            '$'    => '$ (budget)',
            '$$'   => '$$ (moderate)',
            '$$$'  => '$$$ (upscale)',
            '$$$$' => '$$$$ (luxury)',
        ],
    ],
    [
        'key'         => 'specific_serves_cuisine',
        'tab'         => 'schema',
        'section'     => 'business',
        'label'       => 'Cuisine / Serves',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'free',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_available_service',
        'tab'         => 'schema',
        'section'     => 'business',
        'label'       => 'Available Service',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'free',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_star_rating',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Star Rating',
        'type'        => 'select',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
        'options'     => [
            ''  => 'Not specified',
            '1' => '1 Star',
            '2' => '2 Stars',
            '3' => '3 Stars',
            '4' => '4 Stars',
            '5' => '5 Stars',
        ],
    ],
    [
        'key'         => 'specific_checkin_time',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Check-in Time',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_checkout_time',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Check-out Time',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_pets_allowed',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Pets Allowed',
        'type'        => 'select',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
        'options'     => ['' => 'Not specified', 'true' => 'Yes', 'false' => 'No'],
    ],
    [
        'key'         => 'specific_area_served',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Area Served',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_payment_accepted',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Payment Accepted',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_amenity_feature',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Amenity Features',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_job_title',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Job Title',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_affiliation',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Affiliation',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_knows_about',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Topics / Expertise',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_founding_date',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Founding Date',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_masthead_url',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Masthead URL',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'specific_ethics_policy_url',
        'tab'         => 'schema',
        'section'     => 'business_details',
        'label'       => 'Ethics Policy URL',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],

    // ── Organization profile (free) ───────────────────────────────
    [
        'key' => 'org_name', 'tab' => 'org', 'section' => 'identity',
        'label' => 'Organization Name', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_description', 'tab' => 'org', 'section' => 'identity',
        'label' => 'Organization Description', 'type' => 'textarea', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_logo', 'tab' => 'org', 'section' => 'identity',
        'label' => 'Organization Logo', 'type' => 'media', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_url', 'tab' => 'org', 'section' => 'contact',
        'label' => 'Organization URL', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_email', 'tab' => 'org', 'section' => 'contact',
        'label' => 'Email Address', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_phone', 'tab' => 'org', 'section' => 'contact',
        'label' => 'Phone Number', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'social_facebook', 'tab' => 'org', 'section' => 'social',
        'label' => 'Facebook', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'social_instagram', 'tab' => 'org', 'section' => 'social',
        'label' => 'Instagram', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'social_youtube', 'tab' => 'org', 'section' => 'social',
        'label' => 'YouTube', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'social_twitter', 'tab' => 'org', 'section' => 'social',
        'label' => 'Twitter / X', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'social_linkedin', 'tab' => 'org', 'section' => 'social',
        'label' => 'LinkedIn', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'social_tiktok', 'tab' => 'org', 'section' => 'social',
        'label' => 'TikTok', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_address_street', 'tab' => 'org', 'section' => 'address',
        'label' => 'Street Address', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_address_city', 'tab' => 'org', 'section' => 'address',
        'label' => 'City / Locality', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_address_state', 'tab' => 'org', 'section' => 'address',
        'label' => 'State / Region', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_address_zip', 'tab' => 'org', 'section' => 'address',
        'label' => 'Postal Code', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_address_country', 'tab' => 'org', 'section' => 'address',
        'label' => 'Country Code', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_latitude', 'tab' => 'org', 'section' => 'geo',
        'label' => 'Latitude', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'org_longitude', 'tab' => 'org', 'section' => 'geo',
        'label' => 'Longitude', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'rating_value', 'tab' => 'org', 'section' => 'rating',
        'label' => 'Rating Value', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'rating_count', 'tab' => 'org', 'section' => 'rating',
        'label' => 'Review Count', 'type' => 'number', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'rating_best', 'tab' => 'org', 'section' => 'rating',
        'label' => 'Best Rating', 'type' => 'number', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'rating_worst', 'tab' => 'org', 'section' => 'rating',
        'label' => 'Worst Rating', 'type' => 'number', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    [
        'key' => 'rating_source', 'tab' => 'org', 'section' => 'rating',
        'label' => 'Rating Source', 'type' => 'text', 'default' => '',
        'tier' => 'free', 'sku' => 'schema',
    ],
    // Note: the legacy `schema_type_pro_medical` toggle was removed in
    // Task #460 — it was a stale stand-in from before per-value enum
    // gating existed (#459). Medical/Legal/etc. are now part of the
    // `schema_type` dropdown's Pro subset and need no separate flag.

    // ── Author Entity ──────────────────────────────────────────────
    [
        'key'         => 'schema_author_entity_enabled',
        'tab'         => 'schema',
        'section'     => 'author',
        'label'       => 'Emit Person entity for each article author',
        'type'        => 'toggle',
        'default'     => '0',
        'tier'        => 'pro',
        'sku'         => 'schema',
        'description' => 'Reads Joomla user custom fields (aiboost_job_title, _bio, _website, _linkedin, _wikipedia) to build E-E-A-T-grade Person schema.',
    ],

    // ── Opening hours advanced ─────────────────────────────────────
    [
        'key'         => 'schema_hours_mode',
        'tab'         => 'schema',
        'section'     => 'hours',
        'label'       => 'Opening Hours Mode',
        'type'        => 'select',
        'default'     => 'simple',
        'tier'        => 'free',
        'sku'         => 'schema',
        'options'     => [
            'simple'   => 'Simple (one text line)',
            'advanced' => 'Advanced — day-by-day schedule',
            'none'     => 'Not applicable / Hide',
        ],
    ],
    [
        'key'         => 'schema_opening_hours',
        'tab'         => 'schema',
        'section'     => 'hours',
        'label'       => 'Opening Hours Text',
        'type'        => 'text',
        'default'     => '',
        'tier'        => 'free',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'schema_hours_temp_closed',
        'tab'         => 'schema',
        'section'     => 'hours_advanced',
        'label'       => 'Temporarily Closed',
        'type'        => 'toggle',
        'default'     => '0',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'schema_holiday_closed',
        'tab'         => 'schema',
        'section'     => 'hours_advanced',
        'label'       => 'Holiday Closures',
        'type'        => 'textarea',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    ...array_merge(...array_map(
        static fn(string $day): array => [
            [
                'key' => 'hours_' . $day . '_opens', 'tab' => 'schema', 'section' => 'hours_advanced',
                'label' => ucfirst($day) . ' Opens', 'type' => 'text', 'default' => '09:00',
                'tier' => 'pro', 'sku' => 'schema',
            ],
            [
                'key' => 'hours_' . $day . '_closes', 'tab' => 'schema', 'section' => 'hours_advanced',
                'label' => ucfirst($day) . ' Closes', 'type' => 'text', 'default' => '17:00',
                'tier' => 'pro', 'sku' => 'schema',
            ],
            [
                'key' => 'hours_' . $day . '_closed', 'tab' => 'schema', 'section' => 'hours_advanced',
                'label' => ucfirst($day) . ' Closed', 'type' => 'toggle', 'default' => '0',
                'tier' => 'pro', 'sku' => 'schema',
            ],
        ],
        ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']
    )),

    // ── FAQ (Task #473: whole section is Pro) ──────────────────────
    [
        'key'         => 'faq_auto_detect',
        'tab'         => 'schema',
        'section'     => 'faq',
        'label'       => 'Auto-Detect FAQ from Content',
        'type'        => 'toggle',
        'default'     => '1',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'enable_manual_faqs',
        'tab'         => 'schema',
        'section'     => 'faq',
        'label'       => 'Enable Manual FAQs',
        'type'        => 'toggle',
        'default'     => '0',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'manual_faq_scope',
        'tab'         => 'schema',
        'section'     => 'faq',
        'label'       => 'Global FAQ - When to Apply',
        'type'        => 'select',
        'default'     => 'fallback_all',
        'tier'        => 'pro',
        'sku'         => 'schema',
        'options'     => [
            'fallback_all'  => 'Fallback on all pages',
            'always_all'    => 'All pages',
            'fallback_home' => 'Homepage fallback only',
            'always_home'   => 'Homepage only',
            'disabled'      => 'Disabled',
        ],
    ],
    [
        'key'         => 'faq_items',
        'tab'         => 'schema',
        'section'     => 'faq',
        'label'       => 'Manual FAQ Items',
        'type'        => 'json',
        'default'     => '[]',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'schema_faq_output_type',
        'tab'         => 'schema',
        'section'     => 'faq',
        'label'       => 'Schema Output Type',
        'type'        => 'select',
        'default'     => 'faqpage',
        'tier'        => 'pro',
        'sku'         => 'schema',
        'options'     => [
            'faqpage' => 'FAQPage only',
            'qapage'  => 'QAPage only',
            'both'    => 'Both FAQPage and QAPage',
        ],
    ],
    // ── HowTo ──────────────────────────────────────────────────────
    [
        'key'         => 'schema_howto_enabled',
        'tab'         => 'schema',
        'section'     => 'howto',
        'label'       => 'Enable HowTo Schema',
        'type'        => 'toggle',
        'default'     => '0',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'schema_howto',
        'tab'         => 'schema',
        'section'     => 'howto',
        'label'       => 'HowTo payload',
        'type'        => 'json',
        'default'     => '',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    // ── Event ──────────────────────────────────────────────────────
    [
        'key'         => 'events_enabled',
        'tab'         => 'schema',
        'section'     => 'event',
        'label'       => 'Enable Event Schema',
        'type'        => 'toggle',
        'default'     => '0',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'events_category_id',
        'tab'         => 'schema',
        'section'     => 'event',
        'label'       => 'Events Joomla Category ID',
        'type'        => 'number',
        'default'     => '0',
        'tier'        => 'pro',
        'sku'         => 'schema',
    ],
    // ── WebSite + Article (free) ───────────────────────────────────
    [
        'key'         => 'website_schema_enabled',
        'tab'         => 'schema',
        'section'     => 'website',
        'label'       => 'Enable WebSite Schema (homepage only)',
        'type'        => 'toggle',
        'default'     => '1',
        'tier'        => 'free',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'enable_search_action',
        'tab'         => 'schema',
        'section'     => 'website',
        'label'       => 'Include SearchAction',
        'type'        => 'toggle',
        'default'     => '1',
        'tier'        => 'free',
        'sku'         => 'schema',
    ],
    [
        'key'         => 'article_schema_enabled',
        'tab'         => 'schema',
        'section'     => 'article',
        'label'       => 'Enable Article Schema on article pages',
        'type'        => 'toggle',
        'default'     => '1',
        'tier'        => 'free',
        'sku'         => 'schema',
    ],

    // ── Breadcrumb Pro (Task #462 codegen smoke test) ──────────────
    // First field that exercises the new manifest-first codegen path:
    // - PHP handler stub auto-generated at aiboost_schema_pro/src/Features/BreadcrumbPro.php
    // - Health check auto-registered via HealthCheckService::registerFromManifest()
    // - en-GB .ini placeholder keys auto-added
    // The opt-in opening/closing markers below cause build-package-zip.py
    // to strip this whole entry out of the base package ZIP (Task #462). The
    // legacy add-on plugin re-contributes the same field via
    // onAiBoostRegisterFields at runtime.
    // @pro:start
    [
        'key'           => 'schema_breadcrumb_pro',
        'tab'           => 'schema',
        'section'       => 'breadcrumb',
        'label'         => 'Enhanced BreadcrumbList',
        'type'          => 'toggle',
        'default'       => '0',
        'tier'          => 'pro',
        'sku'           => 'schema',
        'description'   => 'Emit a richer BreadcrumbList with per-item images and structured position metadata.',
        'feature_class' => 'BreadcrumbPro',
        'health'        => [
            'id'                => 'info_schema_breadcrumb_pro_active',
            'category'          => 'Schema',
            'message'           => 'Enhanced BreadcrumbList is active. Pages should emit a JSON-LD BreadcrumbList with image and position attributes on every item.',
            'expected_artifact' => 'application/ld+json with @type=BreadcrumbList including itemListElement[].image',
            'fix_actions'       => [
                ['label' => 'Open Schema tab → Breadcrumb', 'target_tab' => 'schema', 'target_field' => 'schema_breadcrumb_pro'],
            ],
        ],
        'i18n'          => [
            'label_key'       => 'PLG_SYSTEM_AIBOOST_SCHEMA_BREADCRUMB_PRO_LABEL',
            'description_key' => 'PLG_SYSTEM_AIBOOST_SCHEMA_BREADCRUMB_PRO_DESC',
        ],
    ],
    // @pro:end
];
