// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/BrandStyleGuide.tsx": () => import("../components/mockups/BrandStyleGuide.tsx"),
  "./components/mockups/website/FullPage.tsx": () => import("../components/mockups/website/FullPage.tsx"),
  "./components/mockups/website/HeroSection.tsx": () => import("../components/mockups/website/HeroSection.tsx"),
  "./components/mockups/website/PricingSection.tsx": () => import("../components/mockups/website/PricingSection.tsx")
};
