<?php

/**
 * JoomlaBoost Debug Script - No Plugin Required
 * 
 * Place this file in staging root to test basic functionality
 * URL: https://staging.offroadserbia.com/joomlaboost-debug.php
 */

header('Content-Type: text/html; charset=utf-8');

?>
<!DOCTYPE html>
<html>

<head>
  <title>JoomlaBoost Debug</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
    }

    .success {
      color: green;
    }

    .error {
      color: red;
    }

    .info {
      color: blue;
    }

    .box {
      border: 1px solid #ddd;
      padding: 15px;
      margin: 10px 0;
    }

    pre {
      background: #f5f5f5;
      padding: 10px;
      overflow-x: auto;
    }
  </style>
</head>

<body>
  <h1>🧪 JoomlaBoost Debug Console</h1>
  <p>Testing basic functionality without plugin installation</p>

  <?php

  echo '<div class="box">';
  echo '<h2>🌍 Environment Detection</h2>';

  $domain = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') .
    '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') . '/';

  echo '<p><strong>Current Domain:</strong> ' . htmlspecialchars($domain) . '</p>';

  $stagingKeywords = ['staging', 'stage', 'dev', 'test', 'localhost'];
  $isStaging = false;
  foreach ($stagingKeywords as $keyword) {
    if (stripos($domain, $keyword) !== false) {
      $isStaging = true;
      break;
    }
  }

  echo '<p><strong>Environment:</strong> <span class="' . ($isStaging ? 'info' : 'success') . '">' .
    ($isStaging ? 'STAGING' : 'PRODUCTION') . '</span></p>';
  echo '</div>';

  // Test robots.txt generation
  echo '<div class="box">';
  echo '<h2>🤖 Robots.txt Generation Test</h2>';

  function generateTestRobots($isStaging, $domain)
  {
    if ($isStaging) {
      return "# JoomlaBoost Robots.txt - STAGING ENVIRONMENT\n"
        . "# This site is not indexed by search engines\n\n"
        . "User-agent: *\n"
        . "Disallow: /\n\n"
        . "# Generated by JoomlaBoost Debug Script\n"
        . "# Generated: " . date('Y-m-d H:i:s T') . "\n";
    } else {
      return "# JoomlaBoost Robots.txt - PRODUCTION ENVIRONMENT\n\n"
        . "User-agent: *\n"
        . "Allow: /\n\n"
        . "# Sitemap\n"
        . "Sitemap: {$domain}sitemap.xml\n\n"
        . "# Generated by JoomlaBoost Debug Script\n"
        . "# Generated: " . date('Y-m-d H:i:s T') . "\n";
    }
  }

  $robotsContent = generateTestRobots($isStaging, $domain);
  echo '<p><strong>Generated robots.txt:</strong></p>';
  echo '<pre>' . htmlspecialchars($robotsContent) . '</pre>';
  echo '</div>';

  // Test sitemap.xml generation
  echo '<div class="box">';
  echo '<h2>🗺️ Sitemap.xml Generation Test</h2>';

  function generateTestSitemap($isStaging, $domain)
  {
    $lastmod = date('Y-m-d\TH:i:s\Z');
    $env = $isStaging ? 'STAGING' : 'PRODUCTION';

    return '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
      . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n"
      . "  <!-- JoomlaBoost Sitemap - {$env} ENVIRONMENT -->\n"
      . "  <url>\n"
      . '    <loc>' . htmlspecialchars($domain) . "</loc>\n"
      . '    <lastmod>' . $lastmod . "</lastmod>\n"
      . "    <changefreq>daily</changefreq>\n"
      . "    <priority>1.0</priority>\n"
      . "  </url>\n"
      . "  <!-- Generated by JoomlaBoost Debug Script -->\n"
      . "  <!-- Generated: " . date('Y-m-d H:i:s T') . " -->\n"
      . "</urlset>";
  }

  $sitemapContent = generateTestSitemap($isStaging, $domain);
  echo '<p><strong>Generated sitemap.xml:</strong></p>';
  echo '<pre>' . htmlspecialchars($sitemapContent) . '</pre>';
  echo '</div>';

  // Server info
  echo '<div class="box">';
  echo '<h2>🔧 Server Information</h2>';
  echo '<p><strong>PHP Version:</strong> ' . PHP_VERSION . '</p>';
  echo '<p><strong>Server Software:</strong> ' . ($_SERVER['SERVER_SOFTWARE'] ?? 'Unknown') . '</p>';
  echo '<p><strong>Request URI:</strong> ' . ($_SERVER['REQUEST_URI'] ?? 'Unknown') . '</p>';
  echo '<p><strong>Document Root:</strong> ' . ($_SERVER['DOCUMENT_ROOT'] ?? 'Unknown') . '</p>';
  echo '</div>';

  // Test URL patterns
  echo '<div class="box">';
  echo '<h2>🔍 URL Pattern Testing</h2>';

  $testUrls = [
    '/robots.txt' => 'robots',
    '/sitemap.xml' => 'sitemap',
    '/?format=robots' => 'robots',
    '/?format=sitemap' => 'sitemap',
    '/index.php' => 'none',
  ];

  echo '<table border="1" cellpadding="5">';
  echo '<tr><th>URL</th><th>Expected</th><th>Result</th><th>Status</th></tr>';

  foreach ($testUrls as $url => $expected) {
    $cleanUri = strtok($url, '?') ?: '';
    $isRobots = preg_match('#/robots\.txt$#i', $cleanUri);
    $isSitemap = preg_match('#/sitemap\.xml$#i', $cleanUri);

    if (!$isRobots && !$isSitemap && strpos($url, '?') !== false) {
      parse_str(parse_url($url, PHP_URL_QUERY) ?: '', $query);
      $isRobots = isset($query['format']) && $query['format'] === 'robots';
      $isSitemap = isset($query['format']) && $query['format'] === 'sitemap';
    }

    $detected = 'none';
    if ($isRobots) $detected = 'robots';
    if ($isSitemap) $detected = 'sitemap';

    $status = ($detected === $expected) ? '✅' : '❌';
    $class = ($detected === $expected) ? 'success' : 'error';

    echo "<tr>";
    echo "<td>$url</td>";
    echo "<td>$expected</td>";
    echo "<td class='$class'>$detected</td>";
    echo "<td>$status</td>";
    echo "</tr>";
  }
  echo '</table>';
  echo '</div>';

  // Test links
  echo '<div class="box">';
  echo '<h2>🔗 Test Links</h2>';
  echo '<p><a href="' . $domain . 'joomlaboost-debug.php?format=robots" target="_blank">Test robots.txt format</a></p>';
  echo '<p><a href="' . $domain . 'joomlaboost-debug.php?format=sitemap" target="_blank">Test sitemap.xml format</a></p>';
  echo '<p><a href="' . $domain . 'robots.txt" target="_blank">Check current robots.txt (will be 404 if plugin not installed)</a></p>';
  echo '<p><a href="' . $domain . 'sitemap.xml" target="_blank">Check current sitemap.xml (will be 404 if plugin not installed)</a></p>';
  echo '</div>';

  // Handle format requests
  if (isset($_GET['format'])) {
    $format = $_GET['format'];

    if ($format === 'robots') {
      header('Content-Type: text/plain');
      echo $robotsContent;
      exit;
    } elseif ($format === 'sitemap') {
      header('Content-Type: application/xml');
      echo $sitemapContent;
      exit;
    }
  }
  ?>

  <div class="box">
    <h2>📋 Next Steps</h2>
    <ol>
      <li>Upload <code>joomlaboost-0.1.17-minimal-test.zip</code> to Joomla Admin</li>
      <li>Install and enable the plugin</li>
      <li>Test <code>/robots.txt</code> and <code>/sitemap.xml</code> endpoints</li>
      <li>If working, upgrade to full plugin version</li>
    </ol>
  </div>

</body>

</html>