# Quick Plugin Functionality Test
# Tests plugin endpoints after installation

param(
    [string]$Domain = "https://staging.offroadserbia.com",
    [string]$PluginName = "JoomlaBoost",
    [switch]$Verbose = $false
)

$ErrorActionPreference = "Continue"

Write-Host "🧪 Quick Plugin Functionality Test" -ForegroundColor Green
Write-Host "==================================" -ForegroundColor Green
Write-Host "Testing domain: $Domain" -ForegroundColor Cyan
Write-Host "Plugin name: $PluginName" -ForegroundColor Cyan
Write-Host ""

# Track test results
$testResults = @()

# Test 1: robots.txt endpoint
Write-Host "1️⃣  Testing robots.txt endpoint..." -ForegroundColor Yellow
try {
    $robotsResponse = Invoke-WebRequest -Uri "$Domain/robots.txt" -UseBasicParsing -TimeoutSec 10
    $robotsContent = $robotsResponse.Content
    
    if ($robotsResponse.StatusCode -eq 200) {
        if ($robotsContent -match $PluginName -or $robotsContent -match "Generated by") {
            Write-Host "   ✅ robots.txt: WORKING - Plugin detected" -ForegroundColor Green
            $testResults += "✅ robots.txt: Working"
            
            if ($Verbose) {
                Write-Host "   📄 Content preview:" -ForegroundColor Gray
                $preview = $robotsContent.Substring(0, [Math]::Min(200, $robotsContent.Length))
                Write-Host "   $preview..." -ForegroundColor Gray
            }
        } else {
            Write-Host "   ⚠️  robots.txt: Responds but no plugin signature" -ForegroundColor Yellow
            $testResults += "⚠️  robots.txt: No plugin signature"
        }
        
        # Check content type
        $contentType = $robotsResponse.Headers['Content-Type']
        if ($contentType -match "text/plain") {
            Write-Host "   ✅ Content-Type: text/plain ✅" -ForegroundColor Green
        } else {
            Write-Host "   ⚠️  Content-Type: $contentType (expected text/plain)" -ForegroundColor Yellow
        }
        
    } else {
        Write-Host "   ❌ robots.txt: HTTP $($robotsResponse.StatusCode)" -ForegroundColor Red
        $testResults += "❌ robots.txt: HTTP $($robotsResponse.StatusCode)"
    }
} catch {
    Write-Host "   ❌ robots.txt: Error - $($_.Exception.Message)" -ForegroundColor Red
    $testResults += "❌ robots.txt: Error"
}

Write-Host ""

# Test 2: sitemap.xml endpoint
Write-Host "2️⃣  Testing sitemap.xml endpoint..." -ForegroundColor Yellow
try {
    $sitemapResponse = Invoke-WebRequest -Uri "$Domain/sitemap.xml" -UseBasicParsing -TimeoutSec 10
    $sitemapContent = $sitemapResponse.Content
    
    if ($sitemapResponse.StatusCode -eq 200) {
        if ($sitemapContent -match $PluginName -or $sitemapContent -match "Generated by" -or $sitemapContent -match "<?xml") {
            Write-Host "   ✅ sitemap.xml: WORKING - Valid XML detected" -ForegroundColor Green
            $testResults += "✅ sitemap.xml: Working"
            
            if ($Verbose) {
                Write-Host "   📄 Content preview:" -ForegroundColor Gray
                $preview = $sitemapContent.Substring(0, [Math]::Min(300, $sitemapContent.Length))
                Write-Host "   $preview..." -ForegroundColor Gray
            }
        } else {
            Write-Host "   ⚠️  sitemap.xml: Responds but content unclear" -ForegroundColor Yellow
            $testResults += "⚠️  sitemap.xml: Unclear content"
        }
        
        # Check content type
        $contentType = $sitemapResponse.Headers['Content-Type']
        if ($contentType -match "application/xml" -or $contentType -match "text/xml") {
            Write-Host "   ✅ Content-Type: $contentType ✅" -ForegroundColor Green
        } else {
            Write-Host "   ⚠️  Content-Type: $contentType (expected XML)" -ForegroundColor Yellow
        }
        
    } else {
        Write-Host "   ❌ sitemap.xml: HTTP $($sitemapResponse.StatusCode)" -ForegroundColor Red
        $testResults += "❌ sitemap.xml: HTTP $($sitemapResponse.StatusCode)"
    }
} catch {
    Write-Host "   ❌ sitemap.xml: Error - $($_.Exception.Message)" -ForegroundColor Red
    $testResults += "❌ sitemap.xml: Error"
}

Write-Host ""

# Test 3: Main site health
Write-Host "3️⃣  Testing main site health..." -ForegroundColor Yellow
try {
    $mainResponse = Invoke-WebRequest -Uri $Domain -UseBasicParsing -TimeoutSec 10
    
    if ($mainResponse.StatusCode -eq 200) {
        Write-Host "   ✅ Main site: HTTP 200 OK" -ForegroundColor Green
        $testResults += "✅ Main site: Working"
        
        # Check for basic HTML structure
        if ($mainResponse.Content -match "<html" -and $mainResponse.Content -match "</html>") {
            Write-Host "   ✅ Main site: Valid HTML structure" -ForegroundColor Green
        } else {
            Write-Host "   ⚠️  Main site: Unusual HTML structure" -ForegroundColor Yellow
        }
        
        # Check response size
        $responseSize = [math]::Round($mainResponse.Content.Length / 1KB, 1)
        Write-Host "   📊 Response size: $responseSize KB" -ForegroundColor Cyan
        
    } else {
        Write-Host "   ❌ Main site: HTTP $($mainResponse.StatusCode)" -ForegroundColor Red
        $testResults += "❌ Main site: HTTP $($mainResponse.StatusCode)"
    }
} catch {
    Write-Host "   ❌ Main site: Error - $($_.Exception.Message)" -ForegroundColor Red
    $testResults += "❌ Main site: Error"
}

Write-Host ""

# Test 4: Environment detection
Write-Host "4️⃣  Testing environment detection..." -ForegroundColor Yellow
$stagingKeywords = @('staging', 'stage', 'dev', 'test', 'localhost')
$isStaging = $false

foreach ($keyword in $stagingKeywords) {
    if ($Domain -match $keyword) {
        $isStaging = $true
        Write-Host "   🎯 Environment: STAGING (detected: $keyword)" -ForegroundColor Blue
        break
    }
}

if (-not $isStaging) {
    Write-Host "   🎯 Environment: PRODUCTION" -ForegroundColor Green
}

# Check if robots.txt content matches environment
try {
    if ($robotsResponse -and $robotsResponse.StatusCode -eq 200) {
        $robotsContent = $robotsResponse.Content
        if ($isStaging) {
            if ($robotsContent -match "Disallow: /" -or $robotsContent -match "staging" -or $robotsContent -match "STAGING") {
                Write-Host "   ✅ Environment detection: Staging rules detected" -ForegroundColor Green
                $testResults += "✅ Environment: Staging detected"
            } else {
                Write-Host "   ⚠️  Environment detection: Staging site but no staging rules" -ForegroundColor Yellow
                $testResults += "⚠️  Environment: Staging rules missing"
            }
        } else {
            if ($robotsContent -match "Allow: /" -or $robotsContent -notmatch "Disallow: /") {
                Write-Host "   ✅ Environment detection: Production rules detected" -ForegroundColor Green
                $testResults += "✅ Environment: Production detected"
            } else {
                Write-Host "   ⚠️  Environment detection: Production site but restrictive rules" -ForegroundColor Yellow
                $testResults += "⚠️  Environment: Production rules unclear"
            }
        }
    }
} catch {
    Write-Host "   ⚠️  Environment detection: Could not verify from robots.txt" -ForegroundColor Yellow
}

Write-Host ""

# Summary
Write-Host "📊 TEST SUMMARY" -ForegroundColor Green
Write-Host "===============" -ForegroundColor Green

$passedTests = ($testResults | Where-Object { $_.StartsWith("✅") }).Count
$warningTests = ($testResults | Where-Object { $_.StartsWith("⚠️") }).Count
$failedTests = ($testResults | Where-Object { $_.StartsWith("❌") }).Count
$totalTests = $testResults.Count

Write-Host "✅ Passed: $passedTests" -ForegroundColor Green
Write-Host "⚠️  Warnings: $warningTests" -ForegroundColor Yellow  
Write-Host "❌ Failed: $failedTests" -ForegroundColor Red
Write-Host "📊 Total: $totalTests tests" -ForegroundColor Cyan

foreach ($result in $testResults) {
    Write-Host "   $result" -ForegroundColor White
}

Write-Host ""

# Overall verdict
if ($failedTests -eq 0 -and $warningTests -eq 0) {
    Write-Host "🎉 ALL TESTS PASSED! Plugin is working perfectly! 🎉" -ForegroundColor Green
} elseif ($failedTests -eq 0) {
    Write-Host "✅ TESTS PASSED with warnings. Plugin is functional but review warnings." -ForegroundColor Yellow
} else {
    Write-Host "❌ TESTS FAILED. Plugin needs attention before production use." -ForegroundColor Red
}

Write-Host ""
Write-Host "🔗 Quick Links:" -ForegroundColor Cyan
Write-Host "   robots.txt: $Domain/robots.txt" -ForegroundColor White
Write-Host "   sitemap.xml: $Domain/sitemap.xml" -ForegroundColor White
Write-Host "   Main site: $Domain" -ForegroundColor White

if ($isStaging) {
    Write-Host ""
    Write-Host "🎯 Next Steps (Staging):" -ForegroundColor Blue
    Write-Host "   1. Fix any failed tests above" -ForegroundColor White
    Write-Host "   2. Test plugin configuration options" -ForegroundColor White
    Write-Host "   3. Deploy to production when ready" -ForegroundColor White
} else {
    Write-Host ""
    Write-Host "🎯 Next Steps (Production):" -ForegroundColor Green
    Write-Host "   1. Monitor plugin performance" -ForegroundColor White
    Write-Host "   2. Check SEO impact" -ForegroundColor White
    Write-Host "   3. Review analytics for improvements" -ForegroundColor White
}
